<?php
/**
 * @file
 * features_tax_category_exportation.features.uuid_term.inc
 */

/**
 * Implements hook_uuid_features_default_terms().
 */
function features_tax_category_exportation_uuid_features_default_terms() {
  $terms = array();

  $terms[] = array(
    'name' => '排卵试纸',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '014d2161-8dac-4586-bac1-3742bcb6fcf6',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => '8f324631-65ae-43df-abfd-e9c60e0c3db6',
    ),
  );
  $terms[] = array(
    'name' => '温度计类',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '02f41043-a316-4c25-aed3-094d886928ea',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => 'a0ef9218-3e77-4be6-8ce2-ecda21c3b99e',
    ),
  );
  $terms[] = array(
    'name' => '阿胶',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => '0',
    'uuid' => '036f1114-f3d3-46ca-9205-70fb8d28fcfa',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => 'a388b9eb-c81d-4639-848d-5b16d4aa253e',
    ),
  );
  $terms[] = array(
    'name' => '美容化妆',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => '0',
    'uuid' => '03a29e1e-6962-4eea-9ab5-f702f7563776',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => '门锁/五金',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '03d4dfe3-0875-42a5-b932-89cdadb969f9',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => '2d2dd18e-434a-4183-9912-c52ffdd71ed9',
    ),
  );
  $terms[] = array(
    'name' => '多层木地板',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '04990feb-b626-4b1f-8472-e4a8b5aa1854',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => '6a7a681e-2233-4e98-8952-20f3d1ad06cc',
    ),
  );
  $terms[] = array(
    'name' => '黄沙',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '08019bf0-dc3f-40da-a14b-3c9c682ce431',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => '9af7546c-57a8-4535-b132-d7a98bc25bde',
    ),
  );
  $terms[] = array(
    'name' => '胶水',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '085295d2-fd88-4632-9255-c429f78575e8',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => '9af7546c-57a8-4535-b132-d7a98bc25bde',
    ),
  );
  $terms[] = array(
    'name' => '鹿茸',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '0b9f08ab-838e-40eb-8677-113227532b7b',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => 'a388b9eb-c81d-4639-848d-5b16d4aa253e',
    ),
  );
  $terms[] = array(
    'name' => '塑胶地板',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '0c42cda5-73cb-4e93-a108-a7af86ec6288',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => '6a7a681e-2233-4e98-8952-20f3d1ad06cc',
    ),
  );
  $terms[] = array(
    'name' => '奶粉',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => '0',
    'uuid' => '0d43173f-8a4e-44e4-95bf-41bb33c6aeaf',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => 'cc4a4d01-f2fe-498b-bb5a-b3ac33f45d3c',
    ),
  );
  $terms[] = array(
    'name' => '家具建材',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => '0',
    'uuid' => '0e7e7f22-560e-4634-93c2-5d99e2ef8631',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => '饰面板',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '0fe31d27-6f32-4f61-af84-18b92bea9d90',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => '4f2fb4fd-152d-4217-8e70-ac054a72a2ac',
    ),
  );
  $terms[] = array(
    'name' => '解热镇痛',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '14318513-f4e1-45ae-9616-ef7d6d1ae293',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => 'b731e9ad-b8e3-43c8-aa75-ebff4b05f4d1',
    ),
  );
  $terms[] = array(
    'name' => 'b族维生素',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '1459e4cf-8064-4145-8b93-cc88def97ccb',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => 'cbb22b1e-dbde-41eb-8275-73fd9cc7339d',
    ),
  );
  $terms[] = array(
    'name' => '保健理疗',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '14a7d1cd-5238-4bff-a335-3058db16c0a9',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => 'a0ef9218-3e77-4be6-8ce2-ecda21c3b99e',
    ),
  );
  $terms[] = array(
    'name' => '蜂蜜',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '16cc442a-6245-4ef6-9ee7-7859ac9004e5',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => 'a388b9eb-c81d-4639-848d-5b16d4aa253e',
    ),
  );
  $terms[] = array(
    'name' => '软木地板',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '16fc5356-d7ed-483b-933d-7555a22308b4',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => '6a7a681e-2233-4e98-8952-20f3d1ad06cc',
    ),
  );
  $terms[] = array(
    'name' => '免漆门',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '188c140c-c6e5-47b5-8fc7-e331c2237dd9',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => '436b370d-f6cb-48d3-b2b5-dab29a1bb460',
    ),
  );
  $terms[] = array(
    'name' => '肠胃用药',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '1a1166d9-6954-4f9c-a772-1b8acf72f16a',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => 'b731e9ad-b8e3-43c8-aa75-ebff4b05f4d1',
    ),
  );
  $terms[] = array(
    'name' => '定制衣柜',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '1bbc102c-de81-45e1-b8a4-b76a99d7c0ee',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => 'e95414b1-c2dd-47e1-b111-48276ef55da9',
    ),
  );
  $terms[] = array(
    'name' => '食品饮料',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => '0',
    'uuid' => '204c8e13-6643-4f27-946d-8214fd2a40f6',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => '戒烟用药',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '21715b91-2ed1-4ef8-a1cf-c6d3a8ff2414',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => 'b731e9ad-b8e3-43c8-aa75-ebff4b05f4d1',
    ),
  );
  $terms[] = array(
    'name' => '防盗窗',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '21ab762d-5a95-4f1f-a5f0-bb9a22881923',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => '516bf28a-4462-4d24-83dd-d0378603cd0d',
    ),
  );
  $terms[] = array(
    'name' => '实木合工艺门',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '26e3061e-4698-4ea2-a8e7-6ab5c105f929',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => '436b370d-f6cb-48d3-b2b5-dab29a1bb460',
    ),
  );
  $terms[] = array(
    'name' => '无框',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '2a55863e-027a-40ea-a219-ab71ec57e270',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => '516bf28a-4462-4d24-83dd-d0378603cd0d',
    ),
  );
  $terms[] = array(
    'name' => '网络线',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '2b67002b-4c4a-4e17-92b3-1807c1c2289c',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => 'bd7f1d57-0def-44b4-9e7f-7c6c67030184',
    ),
  );
  $terms[] = array(
    'name' => '地板漆',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '2b6abc71-4008-4e5c-b86b-2d56287fec56',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => '8b8bf5f2-11f3-4410-99ed-87c52809bc83',
    ),
  );
  $terms[] = array(
    'name' => '体检/检测',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '2c204cc0-2a9d-4e82-8318-59265241c7a2',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => 'a0ef9218-3e77-4be6-8ce2-ecda21c3b99e',
    ),
  );
  $terms[] = array(
    'name' => '五金',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '2d2dd18e-434a-4183-9912-c52ffdd71ed9',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => '0e7e7f22-560e-4634-93c2-5d99e2ef8631',
    ),
  );
  $terms[] = array(
    'name' => '音响线',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '2e600c90-dbe8-452e-a272-bd1af92ad478',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => 'bd7f1d57-0def-44b4-9e7f-7c6c67030184',
    ),
  );
  $terms[] = array(
    'name' => '生活电器',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => '0',
    'uuid' => '2fa0595c-8a93-4464-8909-ef83c5e7c1a1',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => '地漏',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '3027c812-11f4-432b-89b3-7a907afda923',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => '2d2dd18e-434a-4183-9912-c52ffdd71ed9',
    ),
  );
  $terms[] = array(
    'name' => '红景天',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '31a87928-4288-4be0-8f99-d07e79ea43c1',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => 'a388b9eb-c81d-4639-848d-5b16d4aa253e',
    ),
  );
  $terms[] = array(
    'name' => '汽车保养',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => '0',
    'uuid' => '3441f80c-198d-4355-981d-8d19067da876',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => '83492486-830e-4373-aea9-3980e2911af2',
    ),
  );
  $terms[] = array(
    'name' => '下水管配件',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '34d174f0-342e-4f3a-a222-2a40520cad11',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => '2d2dd18e-434a-4183-9912-c52ffdd71ed9',
    ),
  );
  $terms[] = array(
    'name' => '双门',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '35405d58-5618-453f-899c-91127a5d28d6',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => 'fd8e8fc4-6edc-4ce9-b282-b71b86bb8404',
    ),
  );
  $terms[] = array(
    'name' => '高丽参',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '38201b92-d4ce-4b18-b7e9-2ec1a55dd786',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => 'a388b9eb-c81d-4639-848d-5b16d4aa253e',
    ),
  );
  $terms[] = array(
    'name' => '五官用药',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '395f6de1-5afa-4574-8567-8cbeca5d50c9',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => 'b731e9ad-b8e3-43c8-aa75-ebff4b05f4d1',
    ),
  );
  $terms[] = array(
    'name' => '三七',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '39f882ac-21e2-42a5-b502-9796601ce010',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => 'a388b9eb-c81d-4639-848d-5b16d4aa253e',
    ),
  );
  $terms[] = array(
    'name' => '模压门',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '3a6b4eca-aa79-433b-a0e9-0f3c67ad16a9',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => '436b370d-f6cb-48d3-b2b5-dab29a1bb460',
    ),
  );
  $terms[] = array(
    'name' => '布线箱',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '3bdb09a8-6b10-45a8-af3a-ab6a6b6de385',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => '774748e4-a508-4369-b741-510f9ec70340',
    ),
  );
  $terms[] = array(
    'name' => '平板电视',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => '0',
    'uuid' => '400132e7-9602-462e-8516-b361c48bbba3',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => 'f4415198-7ee5-4105-8944-329a1a000524',
    ),
  );
  $terms[] = array(
    'name' => '房门',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '436b370d-f6cb-48d3-b2b5-dab29a1bb460',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => '0e7e7f22-560e-4634-93c2-5d99e2ef8631',
    ),
  );
  $terms[] = array(
    'name' => '水泥',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '437d19a6-c967-4394-abb1-60b3f2aeb07d',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => '9af7546c-57a8-4535-b132-d7a98bc25bde',
    ),
  );
  $terms[] = array(
    'name' => '肝胆用药',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '4711981a-753e-4c46-8cd7-8a44ac3d9ed8',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => 'b731e9ad-b8e3-43c8-aa75-ebff4b05f4d1',
    ),
  );
  $terms[] = array(
    'name' => '补益安神',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '48c3ff68-30b5-414d-a1b3-9569a3b39659',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => 'b731e9ad-b8e3-43c8-aa75-ebff4b05f4d1',
    ),
  );
  $terms[] = array(
    'name' => '木地板',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '4adaac12-9409-4484-a524-187330859a9c',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => '6a7a681e-2233-4e98-8952-20f3d1ad06cc',
    ),
  );
  $terms[] = array(
    'name' => '板材',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '4f2fb4fd-152d-4217-8e70-ac054a72a2ac',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => '0e7e7f22-560e-4634-93c2-5d99e2ef8631',
    ),
  );
  $terms[] = array(
    'name' => '运动户外',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => '0',
    'uuid' => '4fcbbd54-bda7-4129-a744-1ad1c2fbcb88',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => '阳台窗',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '516bf28a-4462-4d24-83dd-d0378603cd0d',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => '0e7e7f22-560e-4634-93c2-5d99e2ef8631',
    ),
  );
  $terms[] = array(
    'name' => '燕窝',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '524325f6-dfbc-4b08-b8a7-32b7fa0217ce',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => 'a388b9eb-c81d-4639-848d-5b16d4aa253e',
    ),
  );
  $terms[] = array(
    'name' => '开关套餐',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '5396d211-6f36-4946-8cb3-7fe61c565505',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => '774748e4-a508-4369-b741-510f9ec70340',
    ),
  );
  $terms[] = array(
    'name' => '铝钛合金',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '5b52368a-af62-4a76-84e6-a025466c2581',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => 'ea13db65-9143-43bd-86ee-43d5f6fdc88d',
    ),
  );
  $terms[] = array(
    'name' => '汽车电子',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => '0',
    'uuid' => '5c12fa15-c1b1-4456-89d5-a1723249e88c',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => '83492486-830e-4373-aea9-3980e2911af2',
    ),
  );
  $terms[] = array(
    'name' => '妇科用药',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '5c6391c6-98d9-4347-8aa8-bbd577c0629f',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => 'b731e9ad-b8e3-43c8-aa75-ebff4b05f4d1',
    ),
  );
  $terms[] = array(
    'name' => '皮肤用药',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '5cab6284-faad-42f9-9613-ae60d66ebc0a',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => 'b731e9ad-b8e3-43c8-aa75-ebff4b05f4d1',
    ),
  );
  $terms[] = array(
    'name' => '维生素c',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '5e057e8b-b2f5-4686-b540-131103ee8891',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => 'cbb22b1e-dbde-41eb-8275-73fd9cc7339d',
    ),
  );
  $terms[] = array(
    'name' => '不锈钢',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '5fc641de-f97f-4d1f-a721-6697146b52c5',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => 'ea13db65-9143-43bd-86ee-43d5f6fdc88d',
    ),
  );
  $terms[] = array(
    'name' => '孕婴用药',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '6089a950-888e-4d9d-afdb-491689ff0250',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => 'b731e9ad-b8e3-43c8-aa75-ebff4b05f4d1',
    ),
  );
  $terms[] = array(
    'name' => '早孕试纸',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '6368c83e-3840-4e94-bbe8-05e4ee68633d',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => '8f324631-65ae-43df-abfd-e9c60e0c3db6',
    ),
  );
  $terms[] = array(
    'name' => '1段奶粉',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => '0',
    'uuid' => '64593455-c46c-4955-82c3-9f007df56cf0',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => '0d43173f-8a4e-44e4-95bf-41bb33c6aeaf',
    ),
  );
  $terms[] = array(
    'name' => '酒店住宿',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => '0',
    'uuid' => '681e4b39-515c-486a-b5b0-d8b68f77c08b',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => '性保健用品',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '68a8c483-f634-405d-ba47-7df75b482b99',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => '8f324631-65ae-43df-abfd-e9c60e0c3db6',
    ),
  );
  $terms[] = array(
    'name' => '单芯线',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '6a4f04d1-e5c8-4605-872a-fed1ddc05779',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => 'bd7f1d57-0def-44b4-9e7f-7c6c67030184',
    ),
  );
  $terms[] = array(
    'name' => '地板',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '6a7a681e-2233-4e98-8952-20f3d1ad06cc',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => '0e7e7f22-560e-4634-93c2-5d99e2ef8631',
    ),
  );
  $terms[] = array(
    'name' => '服装配饰',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => '0',
    'uuid' => '6dfabacf-6448-4b38-9320-b1043536aefc',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => '台灯',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '6e2f6758-9309-4ed6-a902-d43345698959',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => 'a169b11f-5480-455f-aba3-56411dd92b8e',
    ),
  );
  $terms[] = array(
    'name' => '铁皮/石斛',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '705e66f4-e88a-48b9-848c-a16cb2d719e3',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => 'a388b9eb-c81d-4639-848d-5b16d4aa253e',
    ),
  );
  $terms[] = array(
    'name' => '大豆异黄酮',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '73588505-ccbc-467c-bd80-9d557584d550',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => 'cbb22b1e-dbde-41eb-8275-73fd9cc7339d',
    ),
  );
  $terms[] = array(
    'name' => '外墙乳胶漆',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '76673443-d1ee-47a9-b934-58e715a3c766',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => '8b8bf5f2-11f3-4410-99ed-87c52809bc83',
    ),
  );
  $terms[] = array(
    'name' => '断路器',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '769e303e-d0e4-4982-9319-d1edfa0d3d4f',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => '774748e4-a508-4369-b741-510f9ec70340',
    ),
  );
  $terms[] = array(
    'name' => '开关/插座',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '774748e4-a508-4369-b741-510f9ec70340',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => '0e7e7f22-560e-4634-93c2-5d99e2ef8631',
    ),
  );
  $terms[] = array(
    'name' => '胶原蛋白',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '77614358-1a83-419c-a00b-76b334a09b2e',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => 'cbb22b1e-dbde-41eb-8275-73fd9cc7339d',
    ),
  );
  $terms[] = array(
    'name' => '牛奶乳品',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => '0',
    'uuid' => '7b1a1263-9bc3-45b0-b332-e15228cf7a61',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => '204c8e13-6643-4f27-946d-8214fd2a40f6',
    ),
  );
  $terms[] = array(
    'name' => '数码电器',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => '0',
    'uuid' => '7def0fd5-8b70-4a19-9c16-f2fb5891d855',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => '旅游度假',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => '0',
    'uuid' => '7ee5ae51-26ac-4c62-af63-fccee2304c91',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => '橱柜五金',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '8227dae3-e5eb-498c-ace8-a13248031c7d',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => '2d2dd18e-434a-4183-9912-c52ffdd71ed9',
    ),
  );
  $terms[] = array(
    'name' => '汽车用品',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => '0',
    'uuid' => '83492486-830e-4373-aea9-3980e2911af2',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => '血糖仪器',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '83706a8f-45f9-46cc-8b25-ae56c51535b4',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => 'a0ef9218-3e77-4be6-8ce2-ecda21c3b99e',
    ),
  );
  $terms[] = array(
    'name' => '面部护肤',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => '0',
    'uuid' => '843f8b5a-8e1a-4c12-92ae-bf9a9f5dfea4',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => '03a29e1e-6962-4eea-9ab5-f702f7563776',
    ),
  );
  $terms[] = array(
    'name' => '隔断移门',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '85096901-e6ba-4d17-af40-6a28d5aa2cf3',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => 'e95414b1-c2dd-47e1-b111-48276ef55da9',
    ),
  );
  $terms[] = array(
    'name' => '筒灯/射灯',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '86b8d535-c060-4fe4-907d-ce33de75d92b',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => 'a169b11f-5480-455f-aba3-56411dd92b8e',
    ),
  );
  $terms[] = array(
    'name' => '人参',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => '0',
    'uuid' => '881c8b49-d580-4d19-8bfb-2fed7238e042',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => 'a388b9eb-c81d-4639-848d-5b16d4aa253e',
    ),
  );
  $terms[] = array(
    'name' => '手表眼镜',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => '0',
    'uuid' => '88492dac-975b-44e2-9485-015fff1bb3ee',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => '维生素e',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '88fc906d-1d18-439d-b470-2ce048edb7f8',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => 'cbb22b1e-dbde-41eb-8275-73fd9cc7339d',
    ),
  );
  $terms[] = array(
    'name' => '阳光房',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '89469abc-72ad-4d8d-89ad-2ebd6cfc4fa6',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => '516bf28a-4462-4d24-83dd-d0378603cd0d',
    ),
  );
  $terms[] = array(
    'name' => '润滑剂',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '8b261217-8750-47a9-b3e0-bd15ae26ff31',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => '8f324631-65ae-43df-abfd-e9c60e0c3db6',
    ),
  );
  $terms[] = array(
    'name' => '油漆涂料',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '8b8bf5f2-11f3-4410-99ed-87c52809bc83',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => '0e7e7f22-560e-4634-93c2-5d99e2ef8631',
    ),
  );
  $terms[] = array(
    'name' => '卫浴五金',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '8c49327f-5b49-41ef-822d-5d419f157174',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => '2d2dd18e-434a-4183-9912-c52ffdd71ed9',
    ),
  );
  $terms[] = array(
    'name' => '牛奶',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => '0',
    'uuid' => '8e212dcf-ee47-4b01-8151-0a8f736e724b',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => '7b1a1263-9bc3-45b0-b332-e15228cf7a61',
    ),
  );
  $terms[] = array(
    'name' => '计生用品',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '8f324631-65ae-43df-abfd-e9c60e0c3db6',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => 'fcc2a1a3-6a2e-4f02-9b35-6c0c6a43752a',
    ),
  );
  $terms[] = array(
    'name' => '水管',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '91f950f2-d4da-4916-8f40-16b124017a42',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => '0e7e7f22-560e-4634-93c2-5d99e2ef8631',
    ),
  );
  $terms[] = array(
    'name' => '石膏板',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '93406b34-1196-4158-970b-82d82c8367c2',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => '4f2fb4fd-152d-4217-8e70-ac054a72a2ac',
    ),
  );
  $terms[] = array(
    'name' => '竹地板',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '96d0f378-358c-4cd4-a2a0-ef977c6b62ac',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => '6a7a681e-2233-4e98-8952-20f3d1ad06cc',
    ),
  );
  $terms[] = array(
    'name' => '膳食纤维',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '97b54330-6677-4987-9b70-9e68cafc264f',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => 'cbb22b1e-dbde-41eb-8275-73fd9cc7339d',
    ),
  );
  $terms[] = array(
    'name' => '蜂花粉',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '985c8fbf-87d4-45ca-b91a-ecea3b9c119e',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => 'a388b9eb-c81d-4639-848d-5b16d4aa253e',
    ),
  );
  $terms[] = array(
    'name' => '落地灯',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '99302694-ec53-4486-b68f-197779c32592',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => 'a169b11f-5480-455f-aba3-56411dd92b8e',
    ),
  );
  $terms[] = array(
    'name' => '雪蛤',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '99d5b886-d783-4d86-952a-ca89d84f0d6b',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => 'a388b9eb-c81d-4639-848d-5b16d4aa253e',
    ),
  );
  $terms[] = array(
    'name' => '轮椅拐杖',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '9a624c33-ffb6-40b0-90f1-cf7c0d47c299',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => 'a0ef9218-3e77-4be6-8ce2-ecda21c3b99e',
    ),
  );
  $terms[] = array(
    'name' => '辅料',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '9af7546c-57a8-4535-b132-d7a98bc25bde',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => '0e7e7f22-560e-4634-93c2-5d99e2ef8631',
    ),
  );
  $terms[] = array(
    'name' => '细木工板',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '9bc61a76-0cd0-49b2-be04-eab2749c47e0',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => '4f2fb4fd-152d-4217-8e70-ac054a72a2ac',
    ),
  );
  $terms[] = array(
    'name' => '钻石珠宝',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => '0',
    'uuid' => '9cee631c-ce42-47b2-b989-edca0304a3c2',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => 'abd880c4-4e16-4d0d-ae67-94b7a36c60c2',
    ),
  );
  $terms[] = array(
    'name' => '钻石',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => '0',
    'uuid' => '9e04079e-a984-42c5-a807-55ebfa16fed7',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => '9cee631c-ce42-47b2-b989-edca0304a3c2',
    ),
  );
  $terms[] = array(
    'name' => '铝合金',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '9e51e9e4-6637-4199-bed9-0aac5b8e6066',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => 'ea13db65-9143-43bd-86ee-43d5f6fdc88d',
    ),
  );
  $terms[] = array(
    'name' => '防静电地板',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => '9fa5d2d6-1640-4819-93eb-c64705b38f82',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => '6a7a681e-2233-4e98-8952-20f3d1ad06cc',
    ),
  );
  $terms[] = array(
    'name' => '家庭器械',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'a0ef9218-3e77-4be6-8ce2-ecda21c3b99e',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => 'fcc2a1a3-6a2e-4f02-9b35-6c0c6a43752a',
    ),
  );
  $terms[] = array(
    'name' => '灯具',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'a169b11f-5480-455f-aba3-56411dd92b8e',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => '0e7e7f22-560e-4634-93c2-5d99e2ef8631',
    ),
  );
  $terms[] = array(
    'name' => '传统滋补',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => '0',
    'uuid' => 'a388b9eb-c81d-4639-848d-5b16d4aa253e',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => 'fcc2a1a3-6a2e-4f02-9b35-6c0c6a43752a',
    ),
  );
  $terms[] = array(
    'name' => '风湿骨伤',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'a42b6d67-73fc-4f54-a623-936739f21055',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => 'b731e9ad-b8e3-43c8-aa75-ebff4b05f4d1',
    ),
  );
  $terms[] = array(
    'name' => '木器漆',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'a6705cb3-ab70-4b74-96f1-0f462b56a936',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => '8b8bf5f2-11f3-4410-99ed-87c52809bc83',
    ),
  );
  $terms[] = array(
    'name' => '门中门',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'a7c5138e-0105-4df7-a7f3-8f88e7d7fe6c',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => 'fd8e8fc4-6edc-4ce9-b282-b71b86bb8404',
    ),
  );
  $terms[] = array(
    'name' => '泌尿生殖',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'a7f67c0c-2eba-4f0d-89de-3c209bfeeccc',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => 'b731e9ad-b8e3-43c8-aa75-ebff4b05f4d1',
    ),
  );
  $terms[] = array(
    'name' => '地热地板',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'a8be947c-6a4b-43bf-b979-905a6a652674',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => '6a7a681e-2233-4e98-8952-20f3d1ad06cc',
    ),
  );
  $terms[] = array(
    'name' => '手机通讯',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => '0',
    'uuid' => 'a907efac-d882-40a3-92e6-64ef0f452404',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => 'f3b8a2c5-ab85-4047-b601-1ab3539f172a',
    ),
  );
  $terms[] = array(
    'name' => '橡胶地板',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'a9d45bcd-83d6-42bc-90f5-b3b90ac69acb',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => '6a7a681e-2233-4e98-8952-20f3d1ad06cc',
    ),
  );
  $terms[] = array(
    'name' => '珠宝饰品',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => '0',
    'uuid' => 'abd880c4-4e16-4d0d-ae67-94b7a36c60c2',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => '实木地板',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'adf9ca46-c986-4a67-879b-368435262768',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => '6a7a681e-2233-4e98-8952-20f3d1ad06cc',
    ),
  );
  $terms[] = array(
    'name' => '维矿物质',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'ae12d6c0-aab7-45ae-886e-c7956408f821',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => 'b731e9ad-b8e3-43c8-aa75-ebff4b05f4d1',
    ),
  );
  $terms[] = array(
    'name' => '强化复合地板',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'afc5a006-64d6-4120-94a8-00491bd4187a',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => '6a7a681e-2233-4e98-8952-20f3d1ad06cc',
    ),
  );
  $terms[] = array(
    'name' => '复合维生素',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'b00a4c97-e424-4677-969f-0bf688533025',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => 'cbb22b1e-dbde-41eb-8275-73fd9cc7339d',
    ),
  );
  $terms[] = array(
    'name' => '虫草花',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'b0f31f0e-b59d-4ad7-8276-4a167da3f59e',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => 'a388b9eb-c81d-4639-848d-5b16d4aa253e',
    ),
  );
  $terms[] = array(
    'name' => '机油润滑油',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => '0',
    'uuid' => 'b14dc607-b196-4ae1-97b0-dbec257c3783',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => '3441f80c-198d-4355-981d-8d19067da876',
    ),
  );
  $terms[] = array(
    'name' => '卵磷脂',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'b4b69a70-dbc2-4583-b365-3f13670f89b8',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => 'cbb22b1e-dbde-41eb-8275-73fd9cc7339d',
    ),
  );
  $terms[] = array(
    'name' => '口腔护理',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'b57d43ed-8594-4b5a-8d77-fa05077a8fb1',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => 'a0ef9218-3e77-4be6-8ce2-ecda21c3b99e',
    ),
  );
  $terms[] = array(
    'name' => '避孕套',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'b58140db-9446-4a56-8c41-cd4667babe2e',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => '8f324631-65ae-43df-abfd-e9c60e0c3db6',
    ),
  );
  $terms[] = array(
    'name' => '中西药品',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => '0',
    'uuid' => 'b731e9ad-b8e3-43c8-aa75-ebff4b05f4d1',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => 'fcc2a1a3-6a2e-4f02-9b35-6c0c6a43752a',
    ),
  );
  $terms[] = array(
    'name' => '吊灯',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'bbcd74c0-bbb8-4efb-88e9-965633cb65e2',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => 'a169b11f-5480-455f-aba3-56411dd92b8e',
    ),
  );
  $terms[] = array(
    'name' => '刨花板',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'bbf202bb-72e1-49aa-abd7-8ff23bd5aae7',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => '4f2fb4fd-152d-4217-8e70-ac054a72a2ac',
    ),
  );
  $terms[] = array(
    'name' => '内墙乳胶漆',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'bcab9128-b996-4524-a96f-c49265b68977',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => '8b8bf5f2-11f3-4410-99ed-87c52809bc83',
    ),
  );
  $terms[] = array(
    'name' => '电线',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'bd7f1d57-0def-44b4-9e7f-7c6c67030184',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => '0e7e7f22-560e-4634-93c2-5d99e2ef8631',
    ),
  );
  $terms[] = array(
    'name' => '医疗用品',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'be686fdf-cd06-4f41-a671-0d31c1f4faa4',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => 'a0ef9218-3e77-4be6-8ce2-ecda21c3b99e',
    ),
  );
  $terms[] = array(
    'name' => '开关',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'c0101701-10d7-4f58-8a7f-d924a8f6fb4e',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => '774748e4-a508-4369-b741-510f9ec70340',
    ),
  );
  $terms[] = array(
    'name' => '地坪漆',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'c43748ca-5248-44b3-9cab-98b353957f36',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => '8b8bf5f2-11f3-4410-99ed-87c52809bc83',
    ),
  );
  $terms[] = array(
    'name' => '壁灯',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'c5bff778-b401-4661-9f32-ca5cd0bee654',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => 'a169b11f-5480-455f-aba3-56411dd92b8e',
    ),
  );
  $terms[] = array(
    'name' => '保健品',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'cbb22b1e-dbde-41eb-8275-73fd9cc7339d',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => 'fcc2a1a3-6a2e-4f02-9b35-6c0c6a43752a',
    ),
  );
  $terms[] = array(
    'name' => '母婴用品',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => '0',
    'uuid' => 'cc4a4d01-f2fe-498b-bb5a-b3ac33f45d3c',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => '冬虫夏草',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => '0',
    'uuid' => 'cc7c0cae-8431-4fd6-a40f-7ee8da5ad095',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => 'a388b9eb-c81d-4639-848d-5b16d4aa253e',
    ),
  );
  $terms[] = array(
    'name' => '木皮',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'cfed62b0-528b-455e-b3ab-818be510cfbb',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => '4f2fb4fd-152d-4217-8e70-ac054a72a2ac',
    ),
  );
  $terms[] = array(
    'name' => '蛋白粉',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'd0193cd2-be4b-4a60-ab30-eb678d031520',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => 'cbb22b1e-dbde-41eb-8275-73fd9cc7339d',
    ),
  );
  $terms[] = array(
    'name' => '集成材',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'd1afd7da-425c-4385-be63-35ec8537a8ba',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => '4f2fb4fd-152d-4217-8e70-ac054a72a2ac',
    ),
  );
  $terms[] = array(
    'name' => '插座',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'd2fdf7bf-4aff-4fd6-a10f-f82e0f1ad542',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => '774748e4-a508-4369-b741-510f9ec70340',
    ),
  );
  $terms[] = array(
    'name' => '塑料',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'd59237d0-990e-4e3c-89ea-cf6e4927c725',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => 'ea13db65-9143-43bd-86ee-43d5f6fdc88d',
    ),
  );
  $terms[] = array(
    'name' => '血压仪器',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'd61ce3a4-e6dd-4d27-af88-ef356d2c53ea',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => 'a0ef9218-3e77-4be6-8ce2-ecda21c3b99e',
    ),
  );
  $terms[] = array(
    'name' => '单门',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'd8037e92-59fe-4db1-84f2-73233441de2d',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => 'fd8e8fc4-6edc-4ce9-b282-b71b86bb8404',
    ),
  );
  $terms[] = array(
    'name' => '遮阳产品',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'dba4da70-be7d-4f3b-b0b9-7a4ea7a4f02a',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => '516bf28a-4462-4d24-83dd-d0378603cd0d',
    ),
  );
  $terms[] = array(
    'name' => '木方',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'dbd4d07f-7b18-48b3-ad8c-6afcf8849d64',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => '4f2fb4fd-152d-4217-8e70-ac054a72a2ac',
    ),
  );
  $terms[] = array(
    'name' => '接线板',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'dc7ebe50-ed4a-4aed-bc8c-782c4e7167ce',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => '774748e4-a508-4369-b741-510f9ec70340',
    ),
  );
  $terms[] = array(
    'name' => '木塑地板',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'ddb0eea5-e535-4bf4-9304-fd0f71aa18f7',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => '6a7a681e-2233-4e98-8952-20f3d1ad06cc',
    ),
  );
  $terms[] = array(
    'name' => '镁铝合金',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'df262f0a-7efe-4e9b-ae51-c5ff4568b40d',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => 'ea13db65-9143-43bd-86ee-43d5f6fdc88d',
    ),
  );
  $terms[] = array(
    'name' => '洁面',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => '0',
    'uuid' => 'dfe0f34d-b5d1-4482-a7ac-5e9b2457d375',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => '843f8b5a-8e1a-4c12-92ae-bf9a9f5dfea4',
    ),
  );
  $terms[] = array(
    'name' => '感冒咳嗽',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'e0eb7422-413a-4ddc-ad8e-d157c2800968',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => 'b731e9ad-b8e3-43c8-aa75-ebff4b05f4d1',
    ),
  );
  $terms[] = array(
    'name' => '航空铝',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'e15e204a-830d-4302-b39e-3c2d964d5cee',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => 'ea13db65-9143-43bd-86ee-43d5f6fdc88d',
    ),
  );
  $terms[] = array(
    'name' => '子母门',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'e1990294-d777-44e0-9012-84e5ad2c378c',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => 'fd8e8fc4-6edc-4ce9-b282-b71b86bb8404',
    ),
  );
  $terms[] = array(
    'name' => '鞋帽箱包',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => '0',
    'uuid' => 'e1d26445-928e-4871-b3d3-171364af9582',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => '抗菌洗液',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'e20f266f-5824-49fe-9326-f187ab51944e',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => '8f324631-65ae-43df-abfd-e9c60e0c3db6',
    ),
  );
  $terms[] = array(
    'name' => '鱼油',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'e28b85f9-7efc-4771-8d8a-2823d34903fa',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => 'cbb22b1e-dbde-41eb-8275-73fd9cc7339d',
    ),
  );
  $terms[] = array(
    'name' => '有框',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'e445253d-58e0-4817-a3ab-580b63865e1b',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => '516bf28a-4462-4d24-83dd-d0378603cd0d',
    ),
  );
  $terms[] = array(
    'name' => '纱窗',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'e69d1a8f-bfc1-43bd-b314-fd44867f8e7d',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => '516bf28a-4462-4d24-83dd-d0378603cd0d',
    ),
  );
  $terms[] = array(
    'name' => '生态板',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'e6a7db9f-421a-499e-9675-0f9bbbecbe5e',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => '4f2fb4fd-152d-4217-8e70-ac054a72a2ac',
    ),
  );
  $terms[] = array(
    'name' => '吸顶灯',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'e8089167-12ce-4634-9f76-1f9ce1ccf8cc',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => 'a169b11f-5480-455f-aba3-56411dd92b8e',
    ),
  );
  $terms[] = array(
    'name' => '移门衣柜',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'e95414b1-c2dd-47e1-b111-48276ef55da9',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => '0e7e7f22-560e-4634-93c2-5d99e2ef8631',
    ),
  );
  $terms[] = array(
    'name' => '晾衣架',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'ea13db65-9143-43bd-86ee-43d5f6fdc88d',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => '0e7e7f22-560e-4634-93c2-5d99e2ef8631',
    ),
  );
  $terms[] = array(
    'name' => '葡萄籽素',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'eacd9e5c-c988-4dc8-88d5-a9a98b7aeae1',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => 'cbb22b1e-dbde-41eb-8275-73fd9cc7339d',
    ),
  );
  $terms[] = array(
    'name' => '木龙骨',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'eb67b004-b33d-4768-91bc-a272ec86985c',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => '4f2fb4fd-152d-4217-8e70-ac054a72a2ac',
    ),
  );
  $terms[] = array(
    'name' => '石子/砖',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'ebc15863-8b0d-4714-b2d4-70d5458514cd',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => '9af7546c-57a8-4535-b132-d7a98bc25bde',
    ),
  );
  $terms[] = array(
    'name' => '成品衣柜',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'ec248d05-5fe9-4227-b3a7-b2ea98dfdde9',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => 'e95414b1-c2dd-47e1-b111-48276ef55da9',
    ),
  );
  $terms[] = array(
    'name' => '男科用药',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'ec83b780-5f66-4d62-8c98-27e7b3168060',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => 'b731e9ad-b8e3-43c8-aa75-ebff4b05f4d1',
    ),
  );
  $terms[] = array(
    'name' => '整体衣柜',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'ef5be5b9-b6ed-41ca-a0b8-bf9d9de0e277',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => 'e95414b1-c2dd-47e1-b111-48276ef55da9',
    ),
  );
  $terms[] = array(
    'name' => '电话线',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'f12b4851-45ac-44f1-ba0e-4806666d1dc9',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => 'bd7f1d57-0def-44b4-9e7f-7c6c67030184',
    ),
  );
  $terms[] = array(
    'name' => '中医保健',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'f1a852a2-614f-4b91-9ec3-1d740493ebde',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => 'a0ef9218-3e77-4be6-8ce2-ecda21c3b99e',
    ),
  );
  $terms[] = array(
    'name' => '钙',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'f2551fbe-61e4-4841-afa9-cf8cdbad9f13',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => 'cbb22b1e-dbde-41eb-8275-73fd9cc7339d',
    ),
  );
  $terms[] = array(
    'name' => '西洋参',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'f39de332-e425-4090-afe2-fe72dc044c2d',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => 'a388b9eb-c81d-4639-848d-5b16d4aa253e',
    ),
  );
  $terms[] = array(
    'name' => '手机数码',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => '0',
    'uuid' => 'f3b8a2c5-ab85-4047-b601-1ab3539f172a',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => '大家电',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => '0',
    'uuid' => 'f4415198-7ee5-4105-8944-329a1a000524',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => '2fa0595c-8a93-4464-8909-ef83c5e7c1a1',
    ),
  );
  $terms[] = array(
    'name' => '实木原木门',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'f5b6167f-d127-4fc4-82a9-bfebc36dae46',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => '436b370d-f6cb-48d3-b2b5-dab29a1bb460',
    ),
  );
  $terms[] = array(
    'name' => '对开门',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'f6c78cc3-185c-4056-b1d4-ffb5d74419b1',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => 'fd8e8fc4-6edc-4ce9-b282-b71b86bb8404',
    ),
  );
  $terms[] = array(
    'name' => '电缆线',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'fb0c0f38-3d36-4346-934b-1e355fb506c7',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => 'bd7f1d57-0def-44b4-9e7f-7c6c67030184',
    ),
  );
  $terms[] = array(
    'name' => '紧急避孕',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'fb56bd71-cfa2-40af-82a4-179b6bbb5377',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => '8f324631-65ae-43df-abfd-e9c60e0c3db6',
    ),
  );
  $terms[] = array(
    'name' => '医药保健',
    'description' => '',
    'format' => 'filtered_html',
    'weight' => '0',
    'uuid' => 'fcc2a1a3-6a2e-4f02-9b35-6c0c6a43752a',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
  );
  $terms[] = array(
    'name' => '枸杞',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'fcde4d81-c81c-446a-9f00-fcde2bf39c8c',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => 'a388b9eb-c81d-4639-848d-5b16d4aa253e',
    ),
  );
  $terms[] = array(
    'name' => '防盗门',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'fd8e8fc4-6edc-4ce9-b282-b71b86bb8404',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => '0e7e7f22-560e-4634-93c2-5d99e2ef8631',
    ),
  );
  $terms[] = array(
    'name' => '三角阀/煤气阀',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'fe66d558-28ef-4dc5-b59c-c2e5f1a50e53',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => '2d2dd18e-434a-4183-9912-c52ffdd71ed9',
    ),
  );
  $terms[] = array(
    'name' => '眩晕晕车',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'fef85e5a-79fc-4709-9ddf-f2c8e7ff9df8',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => 'b731e9ad-b8e3-43c8-aa75-ebff4b05f4d1',
    ),
  );
  $terms[] = array(
    'name' => '螺旋藻',
    'description' => NULL,
    'format' => NULL,
    'weight' => '0',
    'uuid' => 'ffdc9406-30f2-4552-ad1a-7e4d4d5c1273',
    'vocabulary_machine_name' => 'category',
    'metatags' => array(),
    'parent' => array(
      0 => 'cbb22b1e-dbde-41eb-8275-73fd9cc7339d',
    ),
  );
  return $terms;
}
