<?php
/**
 * @file
 * features_menu_category_exportation.features.menu_links.inc
 */

/**
 * Implements hook_menu_default_menu_links().
 */
function features_menu_category_exportation_menu_default_menu_links() {
  $menu_links = array();

  // Exported menu link: menu-category:taxonomy/term/1
  $menu_links['menu-category:taxonomy/term/1'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/1',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '润唇膏',
    'options' => array(
      'attributes' => array(
        'title' => '润唇膏',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 8,
    'parent_path' => 'taxonomy/term/131',
  );
  // Exported menu link: menu-category:taxonomy/term/10
  $menu_links['menu-category:taxonomy/term/10'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/10',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '门锁/五金',
    'options' => array(
      'attributes' => array(
        'title' => '门锁/五金',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 0,
    'parent_path' => 'taxonomy/term/46',
  );
  // Exported menu link: menu-category:taxonomy/term/100
  $menu_links['menu-category:taxonomy/term/100'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/100',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '孕婴用药',
    'options' => array(
      'attributes' => array(
        'title' => '孕婴用药',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 9,
    'parent_path' => 'taxonomy/term/200',
  );
  // Exported menu link: menu-category:taxonomy/term/101
  $menu_links['menu-category:taxonomy/term/101'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/101',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '早孕试纸',
    'options' => array(
      'attributes' => array(
        'title' => '早孕试纸',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 3,
    'parent_path' => 'taxonomy/term/145',
  );
  // Exported menu link: menu-category:taxonomy/term/102
  $menu_links['menu-category:taxonomy/term/102'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/102',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '1段奶粉',
    'options' => array(
      'attributes' => array(
        'title' => '1段奶粉',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 0,
    'parent_path' => 'taxonomy/term/17',
  );
  // Exported menu link: menu-category:taxonomy/term/103
  $menu_links['menu-category:taxonomy/term/103'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/103',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '婚庆套件',
    'options' => array(
      'attributes' => array(
        'title' => '婚庆套件',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 0,
    'parent_path' => 'taxonomy/term/65',
  );
  // Exported menu link: menu-category:taxonomy/term/104
  $menu_links['menu-category:taxonomy/term/104'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/104',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '精品酒店',
    'options' => array(
      'attributes' => array(
        'title' => '精品酒店',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 1,
    'parent_path' => 'taxonomy/term/106',
  );
  // Exported menu link: menu-category:taxonomy/term/105
  $menu_links['menu-category:taxonomy/term/105'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/105',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '旅游公司',
    'options' => array(
      'attributes' => array(
        'title' => '旅游公司',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 0,
    'parent_path' => 'taxonomy/term/126',
  );
  // Exported menu link: menu-category:taxonomy/term/106
  $menu_links['menu-category:taxonomy/term/106'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/106',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '酒店住宿',
    'options' => array(
      'attributes' => array(
        'title' => '酒店住宿',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => 287,
  );
  // Exported menu link: menu-category:taxonomy/term/107
  $menu_links['menu-category:taxonomy/term/107'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/107',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '性保健用品',
    'options' => array(
      'attributes' => array(
        'title' => '性保健用品',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 0,
    'parent_path' => 'taxonomy/term/145',
  );
  // Exported menu link: menu-category:taxonomy/term/108
  $menu_links['menu-category:taxonomy/term/108'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/108',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '单芯线',
    'options' => array(
      'attributes' => array(
        'title' => '单芯线',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 2,
    'parent_path' => 'taxonomy/term/204',
  );
  // Exported menu link: menu-category:taxonomy/term/109
  $menu_links['menu-category:taxonomy/term/109'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/109',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '地板',
    'options' => array(
      'attributes' => array(
        'title' => '地板',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => 14,
    'parent_path' => 'taxonomy/term/19',
  );
  // Exported menu link: menu-category:taxonomy/term/11
  $menu_links['menu-category:taxonomy/term/11'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/11',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '多层木地板',
    'options' => array(
      'attributes' => array(
        'title' => '多层木地板',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 7,
    'parent_path' => 'taxonomy/term/109',
  );
  // Exported menu link: menu-category:taxonomy/term/110
  $menu_links['menu-category:taxonomy/term/110'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/110',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '浴缸',
    'options' => array(
      'attributes' => array(
        'title' => '浴缸',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 7,
    'parent_path' => 'taxonomy/term/115',
  );
  // Exported menu link: menu-category:taxonomy/term/111
  $menu_links['menu-category:taxonomy/term/111'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/111',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '服装配饰',
    'options' => array(
      'attributes' => array(
        'title' => '服装配饰',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => 280,
  );
  // Exported menu link: menu-category:taxonomy/term/112
  $menu_links['menu-category:taxonomy/term/112'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/112',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '台灯',
    'options' => array(
      'attributes' => array(
        'title' => '台灯',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 0,
    'parent_path' => 'taxonomy/term/166',
  );
  // Exported menu link: menu-category:taxonomy/term/113
  $menu_links['menu-category:taxonomy/term/113'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/113',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '拖把斗',
    'options' => array(
      'attributes' => array(
        'title' => '拖把斗',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 2,
    'parent_path' => 'taxonomy/term/115',
  );
  // Exported menu link: menu-category:taxonomy/term/114
  $menu_links['menu-category:taxonomy/term/114'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/114',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '铁皮/石斛',
    'options' => array(
      'attributes' => array(
        'title' => '铁皮/石斛',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 5,
    'parent_path' => 'taxonomy/term/170',
  );
  // Exported menu link: menu-category:taxonomy/term/115
  $menu_links['menu-category:taxonomy/term/115'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/115',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '卫浴',
    'options' => array(
      'attributes' => array(
        'title' => '卫浴',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => 15,
    'parent_path' => 'taxonomy/term/19',
  );
  // Exported menu link: menu-category:taxonomy/term/116
  $menu_links['menu-category:taxonomy/term/116'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/116',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '毛浴巾',
    'options' => array(
      'attributes' => array(
        'title' => '毛浴巾',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 0,
    'parent_path' => 'taxonomy/term/65',
  );
  // Exported menu link: menu-category:taxonomy/term/117
  $menu_links['menu-category:taxonomy/term/117'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/117',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '大豆异黄酮',
    'options' => array(
      'attributes' => array(
        'title' => '大豆异黄酮',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 3,
    'parent_path' => 'taxonomy/term/217',
  );
  // Exported menu link: menu-category:taxonomy/term/118
  $menu_links['menu-category:taxonomy/term/118'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/118',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '外墙乳胶漆',
    'options' => array(
      'attributes' => array(
        'title' => '外墙乳胶漆',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 0,
    'parent_path' => 'taxonomy/term/141',
  );
  // Exported menu link: menu-category:taxonomy/term/119
  $menu_links['menu-category:taxonomy/term/119'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/119',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '垃圾处理器',
    'options' => array(
      'attributes' => array(
        'title' => '垃圾处理器',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 1,
    'parent_path' => 'taxonomy/term/221',
  );
  // Exported menu link: menu-category:taxonomy/term/12
  $menu_links['menu-category:taxonomy/term/12'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/12',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '仿古砖',
    'options' => array(
      'attributes' => array(
        'title' => '仿古砖',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 6,
    'parent_path' => 'taxonomy/term/68',
  );
  // Exported menu link: menu-category:taxonomy/term/120
  $menu_links['menu-category:taxonomy/term/120'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/120',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '断路器',
    'options' => array(
      'attributes' => array(
        'title' => '断路器',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 5,
    'parent_path' => 'taxonomy/term/121',
  );
  // Exported menu link: menu-category:taxonomy/term/121
  $menu_links['menu-category:taxonomy/term/121'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/121',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '开关/插座',
    'options' => array(
      'attributes' => array(
        'title' => '开关/插座',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => 5,
    'parent_path' => 'taxonomy/term/19',
  );
  // Exported menu link: menu-category:taxonomy/term/122
  $menu_links['menu-category:taxonomy/term/122'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/122',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '胶原蛋白',
    'options' => array(
      'attributes' => array(
        'title' => '胶原蛋白',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 10,
    'parent_path' => 'taxonomy/term/217',
  );
  // Exported menu link: menu-category:taxonomy/term/123
  $menu_links['menu-category:taxonomy/term/123'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/123',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '签证公司',
    'options' => array(
      'attributes' => array(
        'title' => '签证公司',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 1,
    'parent_path' => 'taxonomy/term/126',
  );
  // Exported menu link: menu-category:taxonomy/term/124
  $menu_links['menu-category:taxonomy/term/124'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/124',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '牛奶乳品',
    'options' => array(
      'attributes' => array(
        'title' => '牛奶乳品',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => 0,
    'parent_path' => 'taxonomy/term/33',
  );
  // Exported menu link: menu-category:taxonomy/term/125
  $menu_links['menu-category:taxonomy/term/125'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/125',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '生活电器',
    'options' => array(
      'attributes' => array(
        'title' => '生活电器',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 2,
    'parent_path' => 'taxonomy/term/48',
  );
  // Exported menu link: menu-category:taxonomy/term/126
  $menu_links['menu-category:taxonomy/term/126'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/126',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '旅游度假',
    'options' => array(
      'attributes' => array(
        'title' => '旅游度假',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => 279,
  );
  // Exported menu link: menu-category:taxonomy/term/127
  $menu_links['menu-category:taxonomy/term/127'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/127',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '橱柜五金',
    'options' => array(
      'attributes' => array(
        'title' => '橱柜五金',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 4,
    'parent_path' => 'taxonomy/term/46',
  );
  // Exported menu link: menu-category:taxonomy/term/128
  $menu_links['menu-category:taxonomy/term/128'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/128',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '汽车用品',
    'options' => array(
      'attributes' => array(
        'title' => '汽车用品',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => 282,
  );
  // Exported menu link: menu-category:taxonomy/term/129
  $menu_links['menu-category:taxonomy/term/129'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/129',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '血糖仪器',
    'options' => array(
      'attributes' => array(
        'title' => '血糖仪器',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 4,
    'parent_path' => 'taxonomy/term/165',
  );
  // Exported menu link: menu-category:taxonomy/term/13
  $menu_links['menu-category:taxonomy/term/13'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/13',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '黄沙',
    'options' => array(
      'attributes' => array(
        'title' => '黄沙',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 3,
    'parent_path' => 'taxonomy/term/156',
  );
  // Exported menu link: menu-category:taxonomy/term/130
  $menu_links['menu-category:taxonomy/term/130'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/130',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '手表',
    'options' => array(
      'attributes' => array(
        'title' => '手表',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => 0,
    'parent_path' => 'taxonomy/term/137',
  );
  // Exported menu link: menu-category:taxonomy/term/131
  $menu_links['menu-category:taxonomy/term/131'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/131',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '面部护肤',
    'options' => array(
      'attributes' => array(
        'title' => '面部护肤',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => 0,
    'parent_path' => 'taxonomy/term/9',
  );
  // Exported menu link: menu-category:taxonomy/term/132
  $menu_links['menu-category:taxonomy/term/132'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/132',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '记忆枕',
    'options' => array(
      'attributes' => array(
        'title' => '记忆枕',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 0,
    'parent_path' => 'taxonomy/term/65',
  );
  // Exported menu link: menu-category:taxonomy/term/133
  $menu_links['menu-category:taxonomy/term/133'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/133',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '洗衣柜',
    'options' => array(
      'attributes' => array(
        'title' => '洗衣柜',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 4,
    'parent_path' => 'taxonomy/term/115',
  );
  // Exported menu link: menu-category:taxonomy/term/134
  $menu_links['menu-category:taxonomy/term/134'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/134',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '隔断移门',
    'options' => array(
      'attributes' => array(
        'title' => '隔断移门',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 0,
    'parent_path' => 'taxonomy/term/254',
  );
  // Exported menu link: menu-category:taxonomy/term/135
  $menu_links['menu-category:taxonomy/term/135'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/135',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '筒灯/射灯',
    'options' => array(
      'attributes' => array(
        'title' => '筒灯/射灯',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 4,
    'parent_path' => 'taxonomy/term/166',
  );
  // Exported menu link: menu-category:taxonomy/term/136
  $menu_links['menu-category:taxonomy/term/136'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/136',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '人参',
    'options' => array(
      'attributes' => array(
        'title' => '人参',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 13,
    'parent_path' => 'taxonomy/term/170',
  );
  // Exported menu link: menu-category:taxonomy/term/137
  $menu_links['menu-category:taxonomy/term/137'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/137',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '手表眼镜',
    'options' => array(
      'attributes' => array(
        'title' => '手表眼镜',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => 277,
  );
  // Exported menu link: menu-category:taxonomy/term/138
  $menu_links['menu-category:taxonomy/term/138'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/138',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '维生素e',
    'options' => array(
      'attributes' => array(
        'title' => '维生素e',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 9,
    'parent_path' => 'taxonomy/term/217',
  );
  // Exported menu link: menu-category:taxonomy/term/139
  $menu_links['menu-category:taxonomy/term/139'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/139',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '阳光房',
    'options' => array(
      'attributes' => array(
        'title' => '阳光房',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 5,
    'parent_path' => 'taxonomy/term/82',
  );
  // Exported menu link: menu-category:taxonomy/term/14
  $menu_links['menu-category:taxonomy/term/14'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/14',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '胶水',
    'options' => array(
      'attributes' => array(
        'title' => '胶水',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 2,
    'parent_path' => 'taxonomy/term/156',
  );
  // Exported menu link: menu-category:taxonomy/term/140
  $menu_links['menu-category:taxonomy/term/140'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/140',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '润滑剂',
    'options' => array(
      'attributes' => array(
        'title' => '润滑剂',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 4,
    'parent_path' => 'taxonomy/term/145',
  );
  // Exported menu link: menu-category:taxonomy/term/141
  $menu_links['menu-category:taxonomy/term/141'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/141',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '油漆涂料',
    'options' => array(
      'attributes' => array(
        'title' => '油漆涂料',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => 4,
    'parent_path' => 'taxonomy/term/19',
  );
  // Exported menu link: menu-category:taxonomy/term/142
  $menu_links['menu-category:taxonomy/term/142'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/142',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '卫浴五金',
    'options' => array(
      'attributes' => array(
        'title' => '卫浴五金',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 2,
    'parent_path' => 'taxonomy/term/46',
  );
  // Exported menu link: menu-category:taxonomy/term/143
  $menu_links['menu-category:taxonomy/term/143'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/143',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '居家拖鞋',
    'options' => array(
      'attributes' => array(
        'title' => '居家拖鞋',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 0,
    'parent_path' => 'taxonomy/term/65',
  );
  // Exported menu link: menu-category:taxonomy/term/144
  $menu_links['menu-category:taxonomy/term/144'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/144',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '牛奶',
    'options' => array(
      'attributes' => array(
        'title' => '牛奶',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 0,
    'parent_path' => 'taxonomy/term/124',
  );
  // Exported menu link: menu-category:taxonomy/term/145
  $menu_links['menu-category:taxonomy/term/145'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/145',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '计生用品',
    'options' => array(
      'attributes' => array(
        'title' => '计生用品',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => 4,
    'parent_path' => 'taxonomy/term/280',
  );
  // Exported menu link: menu-category:taxonomy/term/146
  $menu_links['menu-category:taxonomy/term/146'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/146',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '水管',
    'options' => array(
      'attributes' => array(
        'title' => '水管',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 3,
    'parent_path' => 'taxonomy/term/19',
  );
  // Exported menu link: menu-category:taxonomy/term/147
  $menu_links['menu-category:taxonomy/term/147'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/147',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '石膏板',
    'options' => array(
      'attributes' => array(
        'title' => '石膏板',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 4,
    'parent_path' => 'taxonomy/term/80',
  );
  // Exported menu link: menu-category:taxonomy/term/148
  $menu_links['menu-category:taxonomy/term/148'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/148',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '前置过滤器',
    'options' => array(
      'attributes' => array(
        'title' => '前置过滤器',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 0,
    'parent_path' => 'taxonomy/term/221',
  );
  // Exported menu link: menu-category:taxonomy/term/149
  $menu_links['menu-category:taxonomy/term/149'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/149',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '竹地板',
    'options' => array(
      'attributes' => array(
        'title' => '竹地板',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 0,
    'parent_path' => 'taxonomy/term/109',
  );
  // Exported menu link: menu-category:taxonomy/term/15
  $menu_links['menu-category:taxonomy/term/15'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/15',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '鹿茸',
    'options' => array(
      'attributes' => array(
        'title' => '鹿茸',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 0,
    'parent_path' => 'taxonomy/term/170',
  );
  // Exported menu link: menu-category:taxonomy/term/150
  $menu_links['menu-category:taxonomy/term/150'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/150',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '凉席',
    'options' => array(
      'attributes' => array(
        'title' => '凉席',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 0,
    'parent_path' => 'taxonomy/term/65',
  );
  // Exported menu link: menu-category:taxonomy/term/151
  $menu_links['menu-category:taxonomy/term/151'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/151',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '膳食纤维',
    'options' => array(
      'attributes' => array(
        'title' => '膳食纤维',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 11,
    'parent_path' => 'taxonomy/term/217',
  );
  // Exported menu link: menu-category:taxonomy/term/152
  $menu_links['menu-category:taxonomy/term/152'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/152',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '蜂花粉',
    'options' => array(
      'attributes' => array(
        'title' => '蜂花粉',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 7,
    'parent_path' => 'taxonomy/term/170',
  );
  // Exported menu link: menu-category:taxonomy/term/153
  $menu_links['menu-category:taxonomy/term/153'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/153',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '落地灯',
    'options' => array(
      'attributes' => array(
        'title' => '落地灯',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 5,
    'parent_path' => 'taxonomy/term/166',
  );
  // Exported menu link: menu-category:taxonomy/term/154
  $menu_links['menu-category:taxonomy/term/154'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/154',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '雪蛤',
    'options' => array(
      'attributes' => array(
        'title' => '雪蛤',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 2,
    'parent_path' => 'taxonomy/term/170',
  );
  // Exported menu link: menu-category:taxonomy/term/155
  $menu_links['menu-category:taxonomy/term/155'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/155',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '轮椅拐杖',
    'options' => array(
      'attributes' => array(
        'title' => '轮椅拐杖',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 3,
    'parent_path' => 'taxonomy/term/165',
  );
  // Exported menu link: menu-category:taxonomy/term/156
  $menu_links['menu-category:taxonomy/term/156'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/156',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '辅料',
    'options' => array(
      'attributes' => array(
        'title' => '辅料',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => 10,
    'parent_path' => 'taxonomy/term/19',
  );
  // Exported menu link: menu-category:taxonomy/term/157
  $menu_links['menu-category:taxonomy/term/157'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/157',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '细木工板',
    'options' => array(
      'attributes' => array(
        'title' => '细木工板',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 6,
    'parent_path' => 'taxonomy/term/80',
  );
  // Exported menu link: menu-category:taxonomy/term/158
  $menu_links['menu-category:taxonomy/term/158'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/158',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '乳液',
    'options' => array(
      'attributes' => array(
        'title' => '乳液',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 9,
    'parent_path' => 'taxonomy/term/131',
  );
  // Exported menu link: menu-category:taxonomy/term/159
  $menu_links['menu-category:taxonomy/term/159'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/159',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '钻石珠宝',
    'options' => array(
      'attributes' => array(
        'title' => '钻石珠宝',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => 0,
    'parent_path' => 'taxonomy/term/183',
  );
  // Exported menu link: menu-category:taxonomy/term/16
  $menu_links['menu-category:taxonomy/term/16'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/16',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '塑胶地板',
    'options' => array(
      'attributes' => array(
        'title' => '塑胶地板',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 6,
    'parent_path' => 'taxonomy/term/109',
  );
  // Exported menu link: menu-category:taxonomy/term/160
  $menu_links['menu-category:taxonomy/term/160'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/160',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '面包机',
    'options' => array(
      'attributes' => array(
        'title' => '面包机',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 4,
    'parent_path' => 'taxonomy/term/86',
  );
  // Exported menu link: menu-category:taxonomy/term/161
  $menu_links['menu-category:taxonomy/term/161'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/161',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '花草枕',
    'options' => array(
      'attributes' => array(
        'title' => '花草枕',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 0,
    'parent_path' => 'taxonomy/term/65',
  );
  // Exported menu link: menu-category:taxonomy/term/162
  $menu_links['menu-category:taxonomy/term/162'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/162',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '钻石',
    'options' => array(
      'attributes' => array(
        'title' => '钻石',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 0,
    'parent_path' => 'taxonomy/term/159',
  );
  // Exported menu link: menu-category:taxonomy/term/163
  $menu_links['menu-category:taxonomy/term/163'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/163',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '铝合金',
    'options' => array(
      'attributes' => array(
        'title' => '铝合金',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 1,
    'parent_path' => 'taxonomy/term/255',
  );
  // Exported menu link: menu-category:taxonomy/term/164
  $menu_links['menu-category:taxonomy/term/164'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/164',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '防静电地板',
    'options' => array(
      'attributes' => array(
        'title' => '防静电地板',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 3,
    'parent_path' => 'taxonomy/term/109',
  );
  // Exported menu link: menu-category:taxonomy/term/165
  $menu_links['menu-category:taxonomy/term/165'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/165',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '家庭器械',
    'options' => array(
      'attributes' => array(
        'title' => '家庭器械',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => 1,
    'parent_path' => 'taxonomy/term/280',
  );
  // Exported menu link: menu-category:taxonomy/term/166
  $menu_links['menu-category:taxonomy/term/166'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/166',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '灯具',
    'options' => array(
      'attributes' => array(
        'title' => '灯具',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => 2,
    'parent_path' => 'taxonomy/term/19',
  );
  // Exported menu link: menu-category:taxonomy/term/167
  $menu_links['menu-category:taxonomy/term/167'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/167',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '电磁炉',
    'options' => array(
      'attributes' => array(
        'title' => '电磁炉',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 9,
    'parent_path' => 'taxonomy/term/86',
  );
  // Exported menu link: menu-category:taxonomy/term/168
  $menu_links['menu-category:taxonomy/term/168'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/168',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '3D眼镜',
    'options' => array(
      'attributes' => array(
        'title' => '3D眼镜',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 4,
    'parent_path' => 'taxonomy/term/98',
  );
  // Exported menu link: menu-category:taxonomy/term/169
  $menu_links['menu-category:taxonomy/term/169'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/169',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '卸妆',
    'options' => array(
      'attributes' => array(
        'title' => '卸妆',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 6,
    'parent_path' => 'taxonomy/term/131',
  );
  // Exported menu link: menu-category:taxonomy/term/17
  $menu_links['menu-category:taxonomy/term/17'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/17',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '奶粉',
    'options' => array(
      'attributes' => array(
        'title' => '奶粉',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => 0,
    'parent_path' => 'taxonomy/term/218',
  );
  // Exported menu link: menu-category:taxonomy/term/170
  $menu_links['menu-category:taxonomy/term/170'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/170',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '传统滋补',
    'options' => array(
      'attributes' => array(
        'title' => '传统滋补',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => 3,
    'parent_path' => 'taxonomy/term/280',
  );
  // Exported menu link: menu-category:taxonomy/term/171
  $menu_links['menu-category:taxonomy/term/171'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/171',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '春秋毯',
    'options' => array(
      'attributes' => array(
        'title' => '春秋毯',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 0,
    'parent_path' => 'taxonomy/term/65',
  );
  // Exported menu link: menu-category:taxonomy/term/172
  $menu_links['menu-category:taxonomy/term/172'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/172',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '风湿骨伤',
    'options' => array(
      'attributes' => array(
        'title' => '风湿骨伤',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 14,
    'parent_path' => 'taxonomy/term/200',
  );
  // Exported menu link: menu-category:taxonomy/term/173
  $menu_links['menu-category:taxonomy/term/173'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/173',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '木器漆',
    'options' => array(
      'attributes' => array(
        'title' => '木器漆',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 1,
    'parent_path' => 'taxonomy/term/141',
  );
  // Exported menu link: menu-category:taxonomy/term/174
  $menu_links['menu-category:taxonomy/term/174'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/174',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '三星级酒店',
    'options' => array(
      'attributes' => array(
        'title' => '三星级酒店',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 5,
    'parent_path' => 'taxonomy/term/106',
  );
  // Exported menu link: menu-category:taxonomy/term/175
  $menu_links['menu-category:taxonomy/term/175'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/175',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '门中门',
    'options' => array(
      'attributes' => array(
        'title' => '门中门',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 3,
    'parent_path' => 'taxonomy/term/283',
  );
  // Exported menu link: menu-category:taxonomy/term/176
  $menu_links['menu-category:taxonomy/term/176'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/176',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '泌尿生殖',
    'options' => array(
      'attributes' => array(
        'title' => '泌尿生殖',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 1,
    'parent_path' => 'taxonomy/term/200',
  );
  // Exported menu link: menu-category:taxonomy/term/177
  $menu_links['menu-category:taxonomy/term/177'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/177',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '地热地板',
    'options' => array(
      'attributes' => array(
        'title' => '地热地板',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 10,
    'parent_path' => 'taxonomy/term/109',
  );
  // Exported menu link: menu-category:taxonomy/term/178
  $menu_links['menu-category:taxonomy/term/178'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/178',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '手机通讯',
    'options' => array(
      'attributes' => array(
        'title' => '手机通讯',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 0,
    'parent_path' => 'taxonomy/term/271',
  );
  // Exported menu link: menu-category:taxonomy/term/179
  $menu_links['menu-category:taxonomy/term/179'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/179',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '料理机/榨汁机',
    'options' => array(
      'attributes' => array(
        'title' => '料理机/榨汁机',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 13,
    'parent_path' => 'taxonomy/term/86',
  );
  // Exported menu link: menu-category:taxonomy/term/18
  $menu_links['menu-category:taxonomy/term/18'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/18',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '青年旅舍',
    'options' => array(
      'attributes' => array(
        'title' => '青年旅舍',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 3,
    'parent_path' => 'taxonomy/term/106',
  );
  // Exported menu link: menu-category:taxonomy/term/180
  $menu_links['menu-category:taxonomy/term/180'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/180',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '橡胶地板',
    'options' => array(
      'attributes' => array(
        'title' => '橡胶地板',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 1,
    'parent_path' => 'taxonomy/term/109',
  );
  // Exported menu link: menu-category:taxonomy/term/181
  $menu_links['menu-category:taxonomy/term/181'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/181',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '近视眼镜',
    'options' => array(
      'attributes' => array(
        'title' => '近视眼镜',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 5,
    'parent_path' => 'taxonomy/term/98',
  );
  // Exported menu link: menu-category:taxonomy/term/182
  $menu_links['menu-category:taxonomy/term/182'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/182',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '铝扣板',
    'options' => array(
      'attributes' => array(
        'title' => '铝扣板',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 0,
    'parent_path' => 'taxonomy/term/5',
  );
  // Exported menu link: menu-category:taxonomy/term/183
  $menu_links['menu-category:taxonomy/term/183'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/183',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '珠宝饰品',
    'options' => array(
      'attributes' => array(
        'title' => '珠宝饰品',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => 283,
  );
  // Exported menu link: menu-category:taxonomy/term/184
  $menu_links['menu-category:taxonomy/term/184'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/184',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '电脑护目镜',
    'options' => array(
      'attributes' => array(
        'title' => '电脑护目镜',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 1,
    'parent_path' => 'taxonomy/term/98',
  );
  // Exported menu link: menu-category:taxonomy/term/185
  $menu_links['menu-category:taxonomy/term/185'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/185',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '实木地板',
    'options' => array(
      'attributes' => array(
        'title' => '实木地板',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 8,
    'parent_path' => 'taxonomy/term/109',
  );
  // Exported menu link: menu-category:taxonomy/term/186
  $menu_links['menu-category:taxonomy/term/186'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/186',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '维矿物质',
    'options' => array(
      'attributes' => array(
        'title' => '维矿物质',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 4,
    'parent_path' => 'taxonomy/term/200',
  );
  // Exported menu link: menu-category:taxonomy/term/187
  $menu_links['menu-category:taxonomy/term/187'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/187',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '豆浆机',
    'options' => array(
      'attributes' => array(
        'title' => '豆浆机',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 1,
    'parent_path' => 'taxonomy/term/86',
  );
  // Exported menu link: menu-category:taxonomy/term/188
  $menu_links['menu-category:taxonomy/term/188'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/188',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '公寓式酒店',
    'options' => array(
      'attributes' => array(
        'title' => '公寓式酒店',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 7,
    'parent_path' => 'taxonomy/term/106',
  );
  // Exported menu link: menu-category:taxonomy/term/189
  $menu_links['menu-category:taxonomy/term/189'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/189',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '强化复合地板',
    'options' => array(
      'attributes' => array(
        'title' => '强化复合地板',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 9,
    'parent_path' => 'taxonomy/term/109',
  );
  // Exported menu link: menu-category:taxonomy/term/19
  $menu_links['menu-category:taxonomy/term/19'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/19',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '家具建材',
    'options' => array(
      'attributes' => array(
        'title' => '家具建材',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => 275,
  );
  // Exported menu link: menu-category:taxonomy/term/190
  $menu_links['menu-category:taxonomy/term/190'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/190',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '复合维生素',
    'options' => array(
      'attributes' => array(
        'title' => '复合维生素',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 2,
    'parent_path' => 'taxonomy/term/217',
  );
  // Exported menu link: menu-category:taxonomy/term/191
  $menu_links['menu-category:taxonomy/term/191'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/191',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '虫草花',
    'options' => array(
      'attributes' => array(
        'title' => '虫草花',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 8,
    'parent_path' => 'taxonomy/term/170',
  );
  // Exported menu link: menu-category:taxonomy/term/192
  $menu_links['menu-category:taxonomy/term/192'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/192',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '蹲便器',
    'options' => array(
      'attributes' => array(
        'title' => '蹲便器',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 10,
    'parent_path' => 'taxonomy/term/115',
  );
  // Exported menu link: menu-category:taxonomy/term/193
  $menu_links['menu-category:taxonomy/term/193'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/193',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '机油润滑油',
    'options' => array(
      'attributes' => array(
        'title' => '机油润滑油',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 0,
    'parent_path' => 'taxonomy/term/53',
  );
  // Exported menu link: menu-category:taxonomy/term/194
  $menu_links['menu-category:taxonomy/term/194'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/194',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '淋浴房',
    'options' => array(
      'attributes' => array(
        'title' => '淋浴房',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 8,
    'parent_path' => 'taxonomy/term/115',
  );
  // Exported menu link: menu-category:taxonomy/term/195
  $menu_links['menu-category:taxonomy/term/195'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/195',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '全棉四件套',
    'options' => array(
      'attributes' => array(
        'title' => '全棉四件套',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 0,
    'parent_path' => 'taxonomy/term/65',
  );
  // Exported menu link: menu-category:taxonomy/term/196
  $menu_links['menu-category:taxonomy/term/196'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/196',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '浴室柜',
    'options' => array(
      'attributes' => array(
        'title' => '浴室柜',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 6,
    'parent_path' => 'taxonomy/term/115',
  );
  // Exported menu link: menu-category:taxonomy/term/197
  $menu_links['menu-category:taxonomy/term/197'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/197',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '卵磷脂',
    'options' => array(
      'attributes' => array(
        'title' => '卵磷脂',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 1,
    'parent_path' => 'taxonomy/term/217',
  );
  // Exported menu link: menu-category:taxonomy/term/198
  $menu_links['menu-category:taxonomy/term/198'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/198',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '口腔护理',
    'options' => array(
      'attributes' => array(
        'title' => '口腔护理',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 6,
    'parent_path' => 'taxonomy/term/165',
  );
  // Exported menu link: menu-category:taxonomy/term/199
  $menu_links['menu-category:taxonomy/term/199'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/199',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '避孕套',
    'options' => array(
      'attributes' => array(
        'title' => '避孕套',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 6,
    'parent_path' => 'taxonomy/term/145',
  );
  // Exported menu link: menu-category:taxonomy/term/2
  $menu_links['menu-category:taxonomy/term/2'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/2',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '排卵试纸',
    'options' => array(
      'attributes' => array(
        'title' => '排卵试纸',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 2,
    'parent_path' => 'taxonomy/term/145',
  );
  // Exported menu link: menu-category:taxonomy/term/20
  $menu_links['menu-category:taxonomy/term/20'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/20',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '饰面板',
    'options' => array(
      'attributes' => array(
        'title' => '饰面板',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 8,
    'parent_path' => 'taxonomy/term/80',
  );
  // Exported menu link: menu-category:taxonomy/term/200
  $menu_links['menu-category:taxonomy/term/200'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/200',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '中西药品',
    'options' => array(
      'attributes' => array(
        'title' => '中西药品',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => 2,
    'parent_path' => 'taxonomy/term/280',
  );
  // Exported menu link: menu-category:taxonomy/term/201
  $menu_links['menu-category:taxonomy/term/201'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/201',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '吊灯',
    'options' => array(
      'attributes' => array(
        'title' => '吊灯',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 1,
    'parent_path' => 'taxonomy/term/166',
  );
  // Exported menu link: menu-category:taxonomy/term/202
  $menu_links['menu-category:taxonomy/term/202'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/202',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '刨花板',
    'options' => array(
      'attributes' => array(
        'title' => '刨花板',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 5,
    'parent_path' => 'taxonomy/term/80',
  );
  // Exported menu link: menu-category:taxonomy/term/203
  $menu_links['menu-category:taxonomy/term/203'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/203',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '内墙乳胶漆',
    'options' => array(
      'attributes' => array(
        'title' => '内墙乳胶漆',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 4,
    'parent_path' => 'taxonomy/term/141',
  );
  // Exported menu link: menu-category:taxonomy/term/204
  $menu_links['menu-category:taxonomy/term/204'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/204',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '电线',
    'options' => array(
      'attributes' => array(
        'title' => '电线',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => 13,
    'parent_path' => 'taxonomy/term/19',
  );
  // Exported menu link: menu-category:taxonomy/term/205
  $menu_links['menu-category:taxonomy/term/205'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/205',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '医疗用品',
    'options' => array(
      'attributes' => array(
        'title' => '医疗用品',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 5,
    'parent_path' => 'taxonomy/term/165',
  );
  // Exported menu link: menu-category:taxonomy/term/206
  $menu_links['menu-category:taxonomy/term/206'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/206',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '外墙砖',
    'options' => array(
      'attributes' => array(
        'title' => '外墙砖',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 2,
    'parent_path' => 'taxonomy/term/68',
  );
  // Exported menu link: menu-category:taxonomy/term/207
  $menu_links['menu-category:taxonomy/term/207'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/207',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '开关',
    'options' => array(
      'attributes' => array(
        'title' => '开关',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 1,
    'parent_path' => 'taxonomy/term/121',
  );
  // Exported menu link: menu-category:taxonomy/term/208
  $menu_links['menu-category:taxonomy/term/208'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/208',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '酸奶机',
    'options' => array(
      'attributes' => array(
        'title' => '酸奶机',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 2,
    'parent_path' => 'taxonomy/term/86',
  );
  // Exported menu link: menu-category:taxonomy/term/209
  $menu_links['menu-category:taxonomy/term/209'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/209',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '地坪漆',
    'options' => array(
      'attributes' => array(
        'title' => '地坪漆',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 3,
    'parent_path' => 'taxonomy/term/141',
  );
  // Exported menu link: menu-category:taxonomy/term/21
  $menu_links['menu-category:taxonomy/term/21'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/21',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '老花眼镜',
    'options' => array(
      'attributes' => array(
        'title' => '老花眼镜',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 2,
    'parent_path' => 'taxonomy/term/98',
  );
  // Exported menu link: menu-category:taxonomy/term/210
  $menu_links['menu-category:taxonomy/term/210'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/210',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '壁灯',
    'options' => array(
      'attributes' => array(
        'title' => '壁灯',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 3,
    'parent_path' => 'taxonomy/term/166',
  );
  // Exported menu link: menu-category:taxonomy/term/211
  $menu_links['menu-category:taxonomy/term/211'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/211',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '电烤箱',
    'options' => array(
      'attributes' => array(
        'title' => '电烤箱',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 8,
    'parent_path' => 'taxonomy/term/86',
  );
  // Exported menu link: menu-category:taxonomy/term/212
  $menu_links['menu-category:taxonomy/term/212'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/212',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '面膜',
    'options' => array(
      'attributes' => array(
        'title' => '面膜',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 3,
    'parent_path' => 'taxonomy/term/131',
  );
  // Exported menu link: menu-category:taxonomy/term/213
  $menu_links['menu-category:taxonomy/term/213'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/213',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '釉面砖',
    'options' => array(
      'attributes' => array(
        'title' => '釉面砖',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 7,
    'parent_path' => 'taxonomy/term/68',
  );
  // Exported menu link: menu-category:taxonomy/term/214
  $menu_links['menu-category:taxonomy/term/214'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/214',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '枕套',
    'options' => array(
      'attributes' => array(
        'title' => '枕套',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 0,
    'parent_path' => 'taxonomy/term/65',
  );
  // Exported menu link: menu-category:taxonomy/term/215
  $menu_links['menu-category:taxonomy/term/215'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/215',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '智能坐便盖',
    'options' => array(
      'attributes' => array(
        'title' => '智能坐便盖',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 3,
    'parent_path' => 'taxonomy/term/115',
  );
  // Exported menu link: menu-category:taxonomy/term/216
  $menu_links['menu-category:taxonomy/term/216'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/216',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '咖啡机',
    'options' => array(
      'attributes' => array(
        'title' => '咖啡机',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 5,
    'parent_path' => 'taxonomy/term/86',
  );
  // Exported menu link: menu-category:taxonomy/term/217
  $menu_links['menu-category:taxonomy/term/217'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/217',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '保健品',
    'options' => array(
      'attributes' => array(
        'title' => '保健品',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => 0,
    'parent_path' => 'taxonomy/term/280',
  );
  // Exported menu link: menu-category:taxonomy/term/218
  $menu_links['menu-category:taxonomy/term/218'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/218',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '母婴用品',
    'options' => array(
      'attributes' => array(
        'title' => '母婴用品',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => 281,
  );
  // Exported menu link: menu-category:taxonomy/term/219
  $menu_links['menu-category:taxonomy/term/219'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/219',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '冬虫夏草',
    'options' => array(
      'attributes' => array(
        'title' => '冬虫夏草',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 9,
    'parent_path' => 'taxonomy/term/170',
  );
  // Exported menu link: menu-category:taxonomy/term/22
  $menu_links['menu-category:taxonomy/term/22'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/22',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '解热镇痛',
    'options' => array(
      'attributes' => array(
        'title' => '解热镇痛',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 13,
    'parent_path' => 'taxonomy/term/200',
  );
  // Exported menu link: menu-category:taxonomy/term/220
  $menu_links['menu-category:taxonomy/term/220'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/220',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '眼部保养',
    'options' => array(
      'attributes' => array(
        'title' => '眼部保养',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 5,
    'parent_path' => 'taxonomy/term/131',
  );
  // Exported menu link: menu-category:taxonomy/term/221
  $menu_links['menu-category:taxonomy/term/221'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/221',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '净水器',
    'options' => array(
      'attributes' => array(
        'title' => '净水器',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => 18,
    'parent_path' => 'taxonomy/term/19',
  );
  // Exported menu link: menu-category:taxonomy/term/222
  $menu_links['menu-category:taxonomy/term/222'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/222',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '经济型酒店',
    'options' => array(
      'attributes' => array(
        'title' => '经济型酒店',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 2,
    'parent_path' => 'taxonomy/term/106',
  );
  // Exported menu link: menu-category:taxonomy/term/223
  $menu_links['menu-category:taxonomy/term/223'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/223',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '精华',
    'options' => array(
      'attributes' => array(
        'title' => '精华',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 0,
    'parent_path' => 'taxonomy/term/131',
  );
  // Exported menu link: menu-category:taxonomy/term/224
  $menu_links['menu-category:taxonomy/term/224'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/224',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '木皮',
    'options' => array(
      'attributes' => array(
        'title' => '木皮',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 0,
    'parent_path' => 'taxonomy/term/80',
  );
  // Exported menu link: menu-category:taxonomy/term/225
  $menu_links['menu-category:taxonomy/term/225'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/225',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '蛋白粉',
    'options' => array(
      'attributes' => array(
        'title' => '蛋白粉',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 8,
    'parent_path' => 'taxonomy/term/217',
  );
  // Exported menu link: menu-category:taxonomy/term/226
  $menu_links['menu-category:taxonomy/term/226'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/226',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '集成材',
    'options' => array(
      'attributes' => array(
        'title' => '集成材',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 7,
    'parent_path' => 'taxonomy/term/80',
  );
  // Exported menu link: menu-category:taxonomy/term/227
  $menu_links['menu-category:taxonomy/term/227'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/227',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '插座',
    'options' => array(
      'attributes' => array(
        'title' => '插座',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 4,
    'parent_path' => 'taxonomy/term/121',
  );
  // Exported menu link: menu-category:taxonomy/term/228
  $menu_links['menu-category:taxonomy/term/228'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/228',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '床垫',
    'options' => array(
      'attributes' => array(
        'title' => '床垫',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 0,
    'parent_path' => 'taxonomy/term/65',
  );
  // Exported menu link: menu-category:taxonomy/term/229
  $menu_links['menu-category:taxonomy/term/229'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/229',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '电饭煲',
    'options' => array(
      'attributes' => array(
        'title' => '电饭煲',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 3,
    'parent_path' => 'taxonomy/term/86',
  );
  // Exported menu link: menu-category:taxonomy/term/23
  $menu_links['menu-category:taxonomy/term/23'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/23',
    'router_path' => 'taxonomy/term/%',
    'link_title' => 'b族维生素',
    'options' => array(
      'attributes' => array(
        'title' => 'b族维生素',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 0,
    'parent_path' => 'taxonomy/term/217',
  );
  // Exported menu link: menu-category:taxonomy/term/230
  $menu_links['menu-category:taxonomy/term/230'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/230',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '塑料',
    'options' => array(
      'attributes' => array(
        'title' => '塑料',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 4,
    'parent_path' => 'taxonomy/term/255',
  );
  // Exported menu link: menu-category:taxonomy/term/231
  $menu_links['menu-category:taxonomy/term/231'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/231',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '血压仪器',
    'options' => array(
      'attributes' => array(
        'title' => '血压仪器',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 8,
    'parent_path' => 'taxonomy/term/165',
  );
  // Exported menu link: menu-category:taxonomy/term/232
  $menu_links['menu-category:taxonomy/term/232'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/232',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '单门',
    'options' => array(
      'attributes' => array(
        'title' => '单门',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 4,
    'parent_path' => 'taxonomy/term/283',
  );
  // Exported menu link: menu-category:taxonomy/term/233
  $menu_links['menu-category:taxonomy/term/233'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/233',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '淋浴花洒',
    'options' => array(
      'attributes' => array(
        'title' => '淋浴花洒',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 9,
    'parent_path' => 'taxonomy/term/115',
  );
  // Exported menu link: menu-category:taxonomy/term/234
  $menu_links['menu-category:taxonomy/term/234'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/234',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '家纺居家',
    'options' => array(
      'attributes' => array(
        'title' => '家纺居家',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => 65,
  );
  // Exported menu link: menu-category:taxonomy/term/235
  $menu_links['menu-category:taxonomy/term/235'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/235',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '遮阳产品',
    'options' => array(
      'attributes' => array(
        'title' => '遮阳产品',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 3,
    'parent_path' => 'taxonomy/term/82',
  );
  // Exported menu link: menu-category:taxonomy/term/236
  $menu_links['menu-category:taxonomy/term/236'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/236',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '木方',
    'options' => array(
      'attributes' => array(
        'title' => '木方',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 1,
    'parent_path' => 'taxonomy/term/80',
  );
  // Exported menu link: menu-category:taxonomy/term/237
  $menu_links['menu-category:taxonomy/term/237'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/237',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '接线板',
    'options' => array(
      'attributes' => array(
        'title' => '接线板',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 3,
    'parent_path' => 'taxonomy/term/121',
  );
  // Exported menu link: menu-category:taxonomy/term/238
  $menu_links['menu-category:taxonomy/term/238'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/238',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '面霜',
    'options' => array(
      'attributes' => array(
        'title' => '面霜',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 4,
    'parent_path' => 'taxonomy/term/131',
  );
  // Exported menu link: menu-category:taxonomy/term/239
  $menu_links['menu-category:taxonomy/term/239'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/239',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '木塑地板',
    'options' => array(
      'attributes' => array(
        'title' => '木塑地板',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 4,
    'parent_path' => 'taxonomy/term/109',
  );
  // Exported menu link: menu-category:taxonomy/term/24
  $menu_links['menu-category:taxonomy/term/24'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/24',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '保健理疗',
    'options' => array(
      'attributes' => array(
        'title' => '保健理疗',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 2,
    'parent_path' => 'taxonomy/term/165',
  );
  // Exported menu link: menu-category:taxonomy/term/240
  $menu_links['menu-category:taxonomy/term/240'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/240',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '镁铝合金',
    'options' => array(
      'attributes' => array(
        'title' => '镁铝合金',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 3,
    'parent_path' => 'taxonomy/term/255',
  );
  // Exported menu link: menu-category:taxonomy/term/241
  $menu_links['menu-category:taxonomy/term/241'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/241',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '洁面',
    'options' => array(
      'attributes' => array(
        'title' => '洁面',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 7,
    'parent_path' => 'taxonomy/term/131',
  );
  // Exported menu link: menu-category:taxonomy/term/242
  $menu_links['menu-category:taxonomy/term/242'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/242',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '感冒咳嗽',
    'options' => array(
      'attributes' => array(
        'title' => '感冒咳嗽',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 6,
    'parent_path' => 'taxonomy/term/200',
  );
  // Exported menu link: menu-category:taxonomy/term/243
  $menu_links['menu-category:taxonomy/term/243'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/243',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '航空铝',
    'options' => array(
      'attributes' => array(
        'title' => '航空铝',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 0,
    'parent_path' => 'taxonomy/term/255',
  );
  // Exported menu link: menu-category:taxonomy/term/244
  $menu_links['menu-category:taxonomy/term/244'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/244',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '子母门',
    'options' => array(
      'attributes' => array(
        'title' => '子母门',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 0,
    'parent_path' => 'taxonomy/term/283',
  );
  // Exported menu link: menu-category:taxonomy/term/245
  $menu_links['menu-category:taxonomy/term/245'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/245',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '鞋帽箱包',
    'options' => array(
      'attributes' => array(
        'title' => '鞋帽箱包',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => 288,
  );
  // Exported menu link: menu-category:taxonomy/term/246
  $menu_links['menu-category:taxonomy/term/246'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/246',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '抗菌洗液',
    'options' => array(
      'attributes' => array(
        'title' => '抗菌洗液',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 1,
    'parent_path' => 'taxonomy/term/145',
  );
  // Exported menu link: menu-category:taxonomy/term/247
  $menu_links['menu-category:taxonomy/term/247'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/247',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '鱼油',
    'options' => array(
      'attributes' => array(
        'title' => '鱼油',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 6,
    'parent_path' => 'taxonomy/term/217',
  );
  // Exported menu link: menu-category:taxonomy/term/248
  $menu_links['menu-category:taxonomy/term/248'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/248',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '有框',
    'options' => array(
      'attributes' => array(
        'title' => '有框',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 1,
    'parent_path' => 'taxonomy/term/82',
  );
  // Exported menu link: menu-category:taxonomy/term/249
  $menu_links['menu-category:taxonomy/term/249'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/249',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '纱窗',
    'options' => array(
      'attributes' => array(
        'title' => '纱窗',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 2,
    'parent_path' => 'taxonomy/term/82',
  );
  // Exported menu link: menu-category:taxonomy/term/25
  $menu_links['menu-category:taxonomy/term/25'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/25',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '玻化砖',
    'options' => array(
      'attributes' => array(
        'title' => '玻化砖',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 3,
    'parent_path' => 'taxonomy/term/68',
  );
  // Exported menu link: menu-category:taxonomy/term/250
  $menu_links['menu-category:taxonomy/term/250'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/250',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '生态板',
    'options' => array(
      'attributes' => array(
        'title' => '生态板',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 3,
    'parent_path' => 'taxonomy/term/80',
  );
  // Exported menu link: menu-category:taxonomy/term/251
  $menu_links['menu-category:taxonomy/term/251'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/251',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '防晒',
    'options' => array(
      'attributes' => array(
        'title' => '防晒',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 2,
    'parent_path' => 'taxonomy/term/131',
  );
  // Exported menu link: menu-category:taxonomy/term/252
  $menu_links['menu-category:taxonomy/term/252'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/252',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '厨房',
    'options' => array(
      'attributes' => array(
        'title' => '厨房',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => 17,
    'parent_path' => 'taxonomy/term/19',
  );
  // Exported menu link: menu-category:taxonomy/term/253
  $menu_links['menu-category:taxonomy/term/253'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/253',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '吸顶灯',
    'options' => array(
      'attributes' => array(
        'title' => '吸顶灯',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 2,
    'parent_path' => 'taxonomy/term/166',
  );
  // Exported menu link: menu-category:taxonomy/term/254
  $menu_links['menu-category:taxonomy/term/254'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/254',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '移门衣柜',
    'options' => array(
      'attributes' => array(
        'title' => '移门衣柜',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => 12,
    'parent_path' => 'taxonomy/term/19',
  );
  // Exported menu link: menu-category:taxonomy/term/255
  $menu_links['menu-category:taxonomy/term/255'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/255',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '晾衣架',
    'options' => array(
      'attributes' => array(
        'title' => '晾衣架',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => 6,
    'parent_path' => 'taxonomy/term/19',
  );
  // Exported menu link: menu-category:taxonomy/term/256
  $menu_links['menu-category:taxonomy/term/256'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/256',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '葡萄籽素',
    'options' => array(
      'attributes' => array(
        'title' => '葡萄籽素',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 12,
    'parent_path' => 'taxonomy/term/217',
  );
  // Exported menu link: menu-category:taxonomy/term/257
  $menu_links['menu-category:taxonomy/term/257'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/257',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '座便器',
    'options' => array(
      'attributes' => array(
        'title' => '座便器',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 0,
    'parent_path' => 'taxonomy/term/115',
  );
  // Exported menu link: menu-category:taxonomy/term/258
  $menu_links['menu-category:taxonomy/term/258'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/258',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '木龙骨',
    'options' => array(
      'attributes' => array(
        'title' => '木龙骨',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 2,
    'parent_path' => 'taxonomy/term/80',
  );
  // Exported menu link: menu-category:taxonomy/term/259
  $menu_links['menu-category:taxonomy/term/259'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/259',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '石子/砖',
    'options' => array(
      'attributes' => array(
        'title' => '石子/砖',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 1,
    'parent_path' => 'taxonomy/term/156',
  );
  // Exported menu link: menu-category:taxonomy/term/26
  $menu_links['menu-category:taxonomy/term/26'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/26',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '蜂蜜',
    'options' => array(
      'attributes' => array(
        'title' => '蜂蜜',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 3,
    'parent_path' => 'taxonomy/term/170',
  );
  // Exported menu link: menu-category:taxonomy/term/260
  $menu_links['menu-category:taxonomy/term/260'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/260',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '软水机',
    'options' => array(
      'attributes' => array(
        'title' => '软水机',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 3,
    'parent_path' => 'taxonomy/term/221',
  );
  // Exported menu link: menu-category:taxonomy/term/261
  $menu_links['menu-category:taxonomy/term/261'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/261',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '成品衣柜',
    'options' => array(
      'attributes' => array(
        'title' => '成品衣柜',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 2,
    'parent_path' => 'taxonomy/term/254',
  );
  // Exported menu link: menu-category:taxonomy/term/262
  $menu_links['menu-category:taxonomy/term/262'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/262',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '男科用药',
    'options' => array(
      'attributes' => array(
        'title' => '男科用药',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 0,
    'parent_path' => 'taxonomy/term/200',
  );
  // Exported menu link: menu-category:taxonomy/term/263
  $menu_links['menu-category:taxonomy/term/263'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/263',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '龙头',
    'options' => array(
      'attributes' => array(
        'title' => '龙头',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 0,
    'parent_path' => 'taxonomy/term/252',
  );
  // Exported menu link: menu-category:taxonomy/term/264
  $menu_links['menu-category:taxonomy/term/264'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/264',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '整体衣柜',
    'options' => array(
      'attributes' => array(
        'title' => '整体衣柜',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 3,
    'parent_path' => 'taxonomy/term/254',
  );
  // Exported menu link: menu-category:taxonomy/term/265
  $menu_links['menu-category:taxonomy/term/265'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/265',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '地砖',
    'options' => array(
      'attributes' => array(
        'title' => '地砖',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 1,
    'parent_path' => 'taxonomy/term/68',
  );
  // Exported menu link: menu-category:taxonomy/term/266
  $menu_links['menu-category:taxonomy/term/266'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/266',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '夜视镜',
    'options' => array(
      'attributes' => array(
        'title' => '夜视镜',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 3,
    'parent_path' => 'taxonomy/term/98',
  );
  // Exported menu link: menu-category:taxonomy/term/267
  $menu_links['menu-category:taxonomy/term/267'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/267',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '电话线',
    'options' => array(
      'attributes' => array(
        'title' => '电话线',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 4,
    'parent_path' => 'taxonomy/term/204',
  );
  // Exported menu link: menu-category:taxonomy/term/268
  $menu_links['menu-category:taxonomy/term/268'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/268',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '中医保健',
    'options' => array(
      'attributes' => array(
        'title' => '中医保健',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 0,
    'parent_path' => 'taxonomy/term/165',
  );
  // Exported menu link: menu-category:taxonomy/term/269
  $menu_links['menu-category:taxonomy/term/269'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/269',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '钙',
    'options' => array(
      'attributes' => array(
        'title' => '钙',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 5,
    'parent_path' => 'taxonomy/term/217',
  );
  // Exported menu link: menu-category:taxonomy/term/27
  $menu_links['menu-category:taxonomy/term/27'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/27',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '软木地板',
    'options' => array(
      'attributes' => array(
        'title' => '软木地板',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 2,
    'parent_path' => 'taxonomy/term/109',
  );
  // Exported menu link: menu-category:taxonomy/term/270
  $menu_links['menu-category:taxonomy/term/270'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/270',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '西洋参',
    'options' => array(
      'attributes' => array(
        'title' => '西洋参',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 4,
    'parent_path' => 'taxonomy/term/170',
  );
  // Exported menu link: menu-category:taxonomy/term/271
  $menu_links['menu-category:taxonomy/term/271'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/271',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '手机数码',
    'options' => array(
      'attributes' => array(
        'title' => '手机数码',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => 276,
  );
  // Exported menu link: menu-category:taxonomy/term/272
  $menu_links['menu-category:taxonomy/term/272'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/272',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '爽肤水',
    'options' => array(
      'attributes' => array(
        'title' => '爽肤水',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 1,
    'parent_path' => 'taxonomy/term/131',
  );
  // Exported menu link: menu-category:taxonomy/term/273
  $menu_links['menu-category:taxonomy/term/273'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/273',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '大家电',
    'options' => array(
      'attributes' => array(
        'title' => '大家电',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => 0,
    'parent_path' => 'taxonomy/term/48',
  );
  // Exported menu link: menu-category:taxonomy/term/274
  $menu_links['menu-category:taxonomy/term/274'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/274',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '实木原木门',
    'options' => array(
      'attributes' => array(
        'title' => '实木原木门',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 0,
    'parent_path' => 'taxonomy/term/69',
  );
  // Exported menu link: menu-category:taxonomy/term/275
  $menu_links['menu-category:taxonomy/term/275'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/275',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '对开门',
    'options' => array(
      'attributes' => array(
        'title' => '对开门',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 2,
    'parent_path' => 'taxonomy/term/283',
  );
  // Exported menu link: menu-category:taxonomy/term/276
  $menu_links['menu-category:taxonomy/term/276'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/276',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '度假村',
    'options' => array(
      'attributes' => array(
        'title' => '度假村',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 0,
    'parent_path' => 'taxonomy/term/106',
  );
  // Exported menu link: menu-category:taxonomy/term/277
  $menu_links['menu-category:taxonomy/term/277'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/277',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '卫浴五金',
    'options' => array(
      'attributes' => array(
        'title' => '卫浴五金',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 5,
    'parent_path' => 'taxonomy/term/115',
  );
  // Exported menu link: menu-category:taxonomy/term/278
  $menu_links['menu-category:taxonomy/term/278'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/278',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '电缆线',
    'options' => array(
      'attributes' => array(
        'title' => '电缆线',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 3,
    'parent_path' => 'taxonomy/term/204',
  );
  // Exported menu link: menu-category:taxonomy/term/279
  $menu_links['menu-category:taxonomy/term/279'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/279',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '紧急避孕',
    'options' => array(
      'attributes' => array(
        'title' => '紧急避孕',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 5,
    'parent_path' => 'taxonomy/term/145',
  );
  // Exported menu link: menu-category:taxonomy/term/28
  $menu_links['menu-category:taxonomy/term/28'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/28',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '免漆门',
    'options' => array(
      'attributes' => array(
        'title' => '免漆门',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 3,
    'parent_path' => 'taxonomy/term/69',
  );
  // Exported menu link: menu-category:taxonomy/term/280
  $menu_links['menu-category:taxonomy/term/280'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/280',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '医药保健',
    'options' => array(
      'attributes' => array(
        'title' => '医药保健',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => 0,
  );
  // Exported menu link: menu-category:taxonomy/term/281
  $menu_links['menu-category:taxonomy/term/281'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/281',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '蚊帐',
    'options' => array(
      'attributes' => array(
        'title' => '蚊帐',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 0,
    'parent_path' => 'taxonomy/term/65',
  );
  // Exported menu link: menu-category:taxonomy/term/282
  $menu_links['menu-category:taxonomy/term/282'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/282',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '枸杞',
    'options' => array(
      'attributes' => array(
        'title' => '枸杞',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 10,
    'parent_path' => 'taxonomy/term/170',
  );
  // Exported menu link: menu-category:taxonomy/term/283
  $menu_links['menu-category:taxonomy/term/283'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/283',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '防盗门',
    'options' => array(
      'attributes' => array(
        'title' => '防盗门',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => 9,
    'parent_path' => 'taxonomy/term/19',
  );
  // Exported menu link: menu-category:taxonomy/term/284
  $menu_links['menu-category:taxonomy/term/284'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/284',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '煮蛋器',
    'options' => array(
      'attributes' => array(
        'title' => '煮蛋器',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 11,
    'parent_path' => 'taxonomy/term/86',
  );
  // Exported menu link: menu-category:taxonomy/term/285
  $menu_links['menu-category:taxonomy/term/285'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/285',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '三角阀/煤气阀',
    'options' => array(
      'attributes' => array(
        'title' => '三角阀/煤气阀',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 5,
    'parent_path' => 'taxonomy/term/46',
  );
  // Exported menu link: menu-category:taxonomy/term/286
  $menu_links['menu-category:taxonomy/term/286'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/286',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '眩晕晕车',
    'options' => array(
      'attributes' => array(
        'title' => '眩晕晕车',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 3,
    'parent_path' => 'taxonomy/term/200',
  );
  // Exported menu link: menu-category:taxonomy/term/287
  $menu_links['menu-category:taxonomy/term/287'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/287',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '螺旋藻',
    'options' => array(
      'attributes' => array(
        'title' => '螺旋藻',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 7,
    'parent_path' => 'taxonomy/term/217',
  );
  // Exported menu link: menu-category:taxonomy/term/288
  $menu_links['menu-category:taxonomy/term/288'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/288',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '运动鞋服',
    'options' => array(
      'attributes' => array(
        'title' => '运动鞋服',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 0,
    'parent_path' => 'taxonomy/term/81',
  );
  // Exported menu link: menu-category:taxonomy/term/289
  $menu_links['menu-category:taxonomy/term/289'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/289',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '运动用品',
    'options' => array(
      'attributes' => array(
        'title' => '运动用品',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 1,
    'parent_path' => 'taxonomy/term/81',
  );
  // Exported menu link: menu-category:taxonomy/term/29
  $menu_links['menu-category:taxonomy/term/29'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/29',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '光能表',
    'options' => array(
      'attributes' => array(
        'title' => '光能表',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 0,
    'parent_path' => 'taxonomy/term/130',
  );
  // Exported menu link: menu-category:taxonomy/term/290
  $menu_links['menu-category:taxonomy/term/290'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/290',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '户外',
    'options' => array(
      'attributes' => array(
        'title' => '户外',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 2,
    'parent_path' => 'taxonomy/term/81',
  );
  // Exported menu link: menu-category:taxonomy/term/291
  $menu_links['menu-category:taxonomy/term/291'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/291',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '时尚女鞋',
    'options' => array(
      'attributes' => array(
        'title' => '时尚女鞋',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 0,
    'parent_path' => 'taxonomy/term/245',
  );
  // Exported menu link: menu-category:taxonomy/term/292
  $menu_links['menu-category:taxonomy/term/292'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/292',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '流行男鞋',
    'options' => array(
      'attributes' => array(
        'title' => '流行男鞋',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 0,
    'parent_path' => 'taxonomy/term/245',
  );
  // Exported menu link: menu-category:taxonomy/term/293
  $menu_links['menu-category:taxonomy/term/293'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/293',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '潮流女包',
    'options' => array(
      'attributes' => array(
        'title' => '潮流女包',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 0,
    'parent_path' => 'taxonomy/term/245',
  );
  // Exported menu link: menu-category:taxonomy/term/294
  $menu_links['menu-category:taxonomy/term/294'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/294',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '精品男包',
    'options' => array(
      'attributes' => array(
        'title' => '精品男包',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 0,
    'parent_path' => 'taxonomy/term/245',
  );
  // Exported menu link: menu-category:taxonomy/term/295
  $menu_links['menu-category:taxonomy/term/295'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/295',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '旅行箱包',
    'options' => array(
      'attributes' => array(
        'title' => '旅行箱包',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 0,
    'parent_path' => 'taxonomy/term/245',
  );
  // Exported menu link: menu-category:taxonomy/term/296
  $menu_links['menu-category:taxonomy/term/296'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/296',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '钱包卡套',
    'options' => array(
      'attributes' => array(
        'title' => '钱包卡套',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 0,
    'parent_path' => 'taxonomy/term/245',
  );
  // Exported menu link: menu-category:taxonomy/term/297
  $menu_links['menu-category:taxonomy/term/297'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/297',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '品牌女装',
    'options' => array(
      'attributes' => array(
        'title' => '品牌女装',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 0,
    'parent_path' => 'taxonomy/term/111',
  );
  // Exported menu link: menu-category:taxonomy/term/298
  $menu_links['menu-category:taxonomy/term/298'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/298',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '精品男装',
    'options' => array(
      'attributes' => array(
        'title' => '精品男装',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 0,
    'parent_path' => 'taxonomy/term/111',
  );
  // Exported menu link: menu-category:taxonomy/term/299
  $menu_links['menu-category:taxonomy/term/299'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/299',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '精致内衣',
    'options' => array(
      'attributes' => array(
        'title' => '精致内衣',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 0,
    'parent_path' => 'taxonomy/term/111',
  );
  // Exported menu link: menu-category:taxonomy/term/3
  $menu_links['menu-category:taxonomy/term/3'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/3',
    'router_path' => 'taxonomy/term/%',
    'link_title' => 'T区',
    'options' => array(
      'attributes' => array(
        'title' => 'T区',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 10,
    'parent_path' => 'taxonomy/term/131',
  );
  // Exported menu link: menu-category:taxonomy/term/30
  $menu_links['menu-category:taxonomy/term/30'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/30',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '肠胃用药',
    'options' => array(
      'attributes' => array(
        'title' => '肠胃用药',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 11,
    'parent_path' => 'taxonomy/term/200',
  );
  // Exported menu link: menu-category:taxonomy/term/300
  $menu_links['menu-category:taxonomy/term/300'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/300',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '服饰配件',
    'options' => array(
      'attributes' => array(
        'title' => '服饰配件',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 0,
    'parent_path' => 'taxonomy/term/111',
  );
  // Exported menu link: menu-category:taxonomy/term/31
  $menu_links['menu-category:taxonomy/term/31'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/31',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '定制衣柜',
    'options' => array(
      'attributes' => array(
        'title' => '定制衣柜',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 1,
    'parent_path' => 'taxonomy/term/254',
  );
  // Exported menu link: menu-category:taxonomy/term/32
  $menu_links['menu-category:taxonomy/term/32'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/32',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '电水壶/热水瓶',
    'options' => array(
      'attributes' => array(
        'title' => '电水壶/热水瓶',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 7,
    'parent_path' => 'taxonomy/term/86',
  );
  // Exported menu link: menu-category:taxonomy/term/33
  $menu_links['menu-category:taxonomy/term/33'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/33',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '食品饮料',
    'options' => array(
      'attributes' => array(
        'title' => '食品饮料',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => 289,
  );
  // Exported menu link: menu-category:taxonomy/term/34
  $menu_links['menu-category:taxonomy/term/34'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/34',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '春秋被',
    'options' => array(
      'attributes' => array(
        'title' => '春秋被',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 0,
    'parent_path' => 'taxonomy/term/65',
  );
  // Exported menu link: menu-category:taxonomy/term/35
  $menu_links['menu-category:taxonomy/term/35'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/35',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '石英表',
    'options' => array(
      'attributes' => array(
        'title' => '石英表',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 3,
    'parent_path' => 'taxonomy/term/130',
  );
  // Exported menu link: menu-category:taxonomy/term/36
  $menu_links['menu-category:taxonomy/term/36'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/36',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '戒烟用药',
    'options' => array(
      'attributes' => array(
        'title' => '戒烟用药',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 5,
    'parent_path' => 'taxonomy/term/200',
  );
  // Exported menu link: menu-category:taxonomy/term/37
  $menu_links['menu-category:taxonomy/term/37'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/37',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '防盗窗',
    'options' => array(
      'attributes' => array(
        'title' => '防盗窗',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 4,
    'parent_path' => 'taxonomy/term/82',
  );
  // Exported menu link: menu-category:taxonomy/term/38
  $menu_links['menu-category:taxonomy/term/38'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/38',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '旅游网站',
    'options' => array(
      'attributes' => array(
        'title' => '旅游网站',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 2,
    'parent_path' => 'taxonomy/term/126',
  );
  // Exported menu link: menu-category:taxonomy/term/39
  $menu_links['menu-category:taxonomy/term/39'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/39',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '实木合工艺门',
    'options' => array(
      'attributes' => array(
        'title' => '实木合工艺门',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 1,
    'parent_path' => 'taxonomy/term/69',
  );
  // Exported menu link: menu-category:taxonomy/term/4
  $menu_links['menu-category:taxonomy/term/4'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/4',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '台盆/立柱',
    'options' => array(
      'attributes' => array(
        'title' => '台盆/立柱',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 1,
    'parent_path' => 'taxonomy/term/115',
  );
  // Exported menu link: menu-category:taxonomy/term/40
  $menu_links['menu-category:taxonomy/term/40'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/40',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '墙砖',
    'options' => array(
      'attributes' => array(
        'title' => '墙砖',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 0,
    'parent_path' => 'taxonomy/term/68',
  );
  // Exported menu link: menu-category:taxonomy/term/41
  $menu_links['menu-category:taxonomy/term/41'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/41',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '无框',
    'options' => array(
      'attributes' => array(
        'title' => '无框',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 0,
    'parent_path' => 'taxonomy/term/82',
  );
  // Exported menu link: menu-category:taxonomy/term/42
  $menu_links['menu-category:taxonomy/term/42'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/42',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '太阳眼镜',
    'options' => array(
      'attributes' => array(
        'title' => '太阳眼镜',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 0,
    'parent_path' => 'taxonomy/term/98',
  );
  // Exported menu link: menu-category:taxonomy/term/43
  $menu_links['menu-category:taxonomy/term/43'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/43',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '网络线',
    'options' => array(
      'attributes' => array(
        'title' => '网络线',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 1,
    'parent_path' => 'taxonomy/term/204',
  );
  // Exported menu link: menu-category:taxonomy/term/44
  $menu_links['menu-category:taxonomy/term/44'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/44',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '地板漆',
    'options' => array(
      'attributes' => array(
        'title' => '地板漆',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 2,
    'parent_path' => 'taxonomy/term/141',
  );
  // Exported menu link: menu-category:taxonomy/term/45
  $menu_links['menu-category:taxonomy/term/45'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/45',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '体检/检测',
    'options' => array(
      'attributes' => array(
        'title' => '体检/检测',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 1,
    'parent_path' => 'taxonomy/term/165',
  );
  // Exported menu link: menu-category:taxonomy/term/46
  $menu_links['menu-category:taxonomy/term/46'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/46',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '五金',
    'options' => array(
      'attributes' => array(
        'title' => '五金',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => 19,
    'parent_path' => 'taxonomy/term/19',
  );
  // Exported menu link: menu-category:taxonomy/term/47
  $menu_links['menu-category:taxonomy/term/47'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/47',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '音响线',
    'options' => array(
      'attributes' => array(
        'title' => '音响线',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 0,
    'parent_path' => 'taxonomy/term/204',
  );
  // Exported menu link: menu-category:taxonomy/term/48
  $menu_links['menu-category:taxonomy/term/48'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/48',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '家用电器',
    'options' => array(
      'attributes' => array(
        'title' => '家用电器',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => 284,
  );
  // Exported menu link: menu-category:taxonomy/term/49
  $menu_links['menu-category:taxonomy/term/49'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/49',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '被套',
    'options' => array(
      'attributes' => array(
        'title' => '被套',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 0,
    'parent_path' => 'taxonomy/term/65',
  );
  // Exported menu link: menu-category:taxonomy/term/5
  $menu_links['menu-category:taxonomy/term/5'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/5',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '吊顶',
    'options' => array(
      'attributes' => array(
        'title' => '吊顶',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => 16,
    'parent_path' => 'taxonomy/term/19',
  );
  // Exported menu link: menu-category:taxonomy/term/50
  $menu_links['menu-category:taxonomy/term/50'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/50',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '地漏',
    'options' => array(
      'attributes' => array(
        'title' => '地漏',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 3,
    'parent_path' => 'taxonomy/term/46',
  );
  // Exported menu link: menu-category:taxonomy/term/51
  $menu_links['menu-category:taxonomy/term/51'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/51',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '电饼铛/煎烤机',
    'options' => array(
      'attributes' => array(
        'title' => '电饼铛/煎烤机',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 0,
    'parent_path' => 'taxonomy/term/86',
  );
  // Exported menu link: menu-category:taxonomy/term/52
  $menu_links['menu-category:taxonomy/term/52'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/52',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '红景天',
    'options' => array(
      'attributes' => array(
        'title' => '红景天',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 12,
    'parent_path' => 'taxonomy/term/170',
  );
  // Exported menu link: menu-category:taxonomy/term/53
  $menu_links['menu-category:taxonomy/term/53'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/53',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '汽车保养',
    'options' => array(
      'attributes' => array(
        'title' => '汽车保养',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => 1,
    'parent_path' => 'taxonomy/term/128',
  );
  // Exported menu link: menu-category:taxonomy/term/54
  $menu_links['menu-category:taxonomy/term/54'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/54',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '下水管配件',
    'options' => array(
      'attributes' => array(
        'title' => '下水管配件',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 1,
    'parent_path' => 'taxonomy/term/46',
  );
  // Exported menu link: menu-category:taxonomy/term/55
  $menu_links['menu-category:taxonomy/term/55'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/55',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '双门',
    'options' => array(
      'attributes' => array(
        'title' => '双门',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 1,
    'parent_path' => 'taxonomy/term/283',
  );
  // Exported menu link: menu-category:taxonomy/term/56
  $menu_links['menu-category:taxonomy/term/56'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/56',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '高丽参',
    'options' => array(
      'attributes' => array(
        'title' => '高丽参',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 1,
    'parent_path' => 'taxonomy/term/170',
  );
  // Exported menu link: menu-category:taxonomy/term/57
  $menu_links['menu-category:taxonomy/term/57'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/57',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '五官用药',
    'options' => array(
      'attributes' => array(
        'title' => '五官用药',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 7,
    'parent_path' => 'taxonomy/term/200',
  );
  // Exported menu link: menu-category:taxonomy/term/58
  $menu_links['menu-category:taxonomy/term/58'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/58',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '三七',
    'options' => array(
      'attributes' => array(
        'title' => '三七',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 14,
    'parent_path' => 'taxonomy/term/170',
  );
  // Exported menu link: menu-category:taxonomy/term/59
  $menu_links['menu-category:taxonomy/term/59'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/59',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '模压门',
    'options' => array(
      'attributes' => array(
        'title' => '模压门',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 2,
    'parent_path' => 'taxonomy/term/69',
  );
  // Exported menu link: menu-category:taxonomy/term/6
  $menu_links['menu-category:taxonomy/term/6'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/6',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '温度计类',
    'options' => array(
      'attributes' => array(
        'title' => '温度计类',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 7,
    'parent_path' => 'taxonomy/term/165',
  );
  // Exported menu link: menu-category:taxonomy/term/60
  $menu_links['menu-category:taxonomy/term/60'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/60',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '水槽',
    'options' => array(
      'attributes' => array(
        'title' => '水槽',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 1,
    'parent_path' => 'taxonomy/term/252',
  );
  // Exported menu link: menu-category:taxonomy/term/61
  $menu_links['menu-category:taxonomy/term/61'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/61',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '布线箱',
    'options' => array(
      'attributes' => array(
        'title' => '布线箱',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 0,
    'parent_path' => 'taxonomy/term/121',
  );
  // Exported menu link: menu-category:taxonomy/term/62
  $menu_links['menu-category:taxonomy/term/62'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/62',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '阳台砖',
    'options' => array(
      'attributes' => array(
        'title' => '阳台砖',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 8,
    'parent_path' => 'taxonomy/term/68',
  );
  // Exported menu link: menu-category:taxonomy/term/63
  $menu_links['menu-category:taxonomy/term/63'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/63',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '机械表',
    'options' => array(
      'attributes' => array(
        'title' => '机械表',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 1,
    'parent_path' => 'taxonomy/term/130',
  );
  // Exported menu link: menu-category:taxonomy/term/64
  $menu_links['menu-category:taxonomy/term/64'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/64',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '床单',
    'options' => array(
      'attributes' => array(
        'title' => '床单',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 0,
    'parent_path' => 'taxonomy/term/65',
  );
  // Exported menu link: menu-category:taxonomy/term/65
  $menu_links['menu-category:taxonomy/term/65'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/65',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '精品家纺',
    'options' => array(
      'attributes' => array(
        'title' => '精品家纺',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => 0,
    'parent_path' => 'taxonomy/term/234',
  );
  // Exported menu link: menu-category:taxonomy/term/66
  $menu_links['menu-category:taxonomy/term/66'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/66',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '平板电视',
    'options' => array(
      'attributes' => array(
        'title' => '平板电视',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 0,
    'parent_path' => 'taxonomy/term/273',
  );
  // Exported menu link: menu-category:taxonomy/term/67
  $menu_links['menu-category:taxonomy/term/67'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/67',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '四星级酒店',
    'options' => array(
      'attributes' => array(
        'title' => '四星级酒店',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 4,
    'parent_path' => 'taxonomy/term/106',
  );
  // Exported menu link: menu-category:taxonomy/term/68
  $menu_links['menu-category:taxonomy/term/68'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/68',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '瓷砖',
    'options' => array(
      'attributes' => array(
        'title' => '瓷砖',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => 11,
    'parent_path' => 'taxonomy/term/19',
  );
  // Exported menu link: menu-category:taxonomy/term/69
  $menu_links['menu-category:taxonomy/term/69'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/69',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '房门',
    'options' => array(
      'attributes' => array(
        'title' => '房门',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => 7,
    'parent_path' => 'taxonomy/term/19',
  );
  // Exported menu link: menu-category:taxonomy/term/7
  $menu_links['menu-category:taxonomy/term/7'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/7',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '花砖',
    'options' => array(
      'attributes' => array(
        'title' => '花砖',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 4,
    'parent_path' => 'taxonomy/term/68',
  );
  // Exported menu link: menu-category:taxonomy/term/70
  $menu_links['menu-category:taxonomy/term/70'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/70',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '水泥',
    'options' => array(
      'attributes' => array(
        'title' => '水泥',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 0,
    'parent_path' => 'taxonomy/term/156',
  );
  // Exported menu link: menu-category:taxonomy/term/71
  $menu_links['menu-category:taxonomy/term/71'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/71',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '墙纸',
    'options' => array(
      'attributes' => array(
        'title' => '墙纸',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 0,
    'parent_path' => 'taxonomy/term/19',
  );
  // Exported menu link: menu-category:taxonomy/term/72
  $menu_links['menu-category:taxonomy/term/72'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/72',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '微波炉',
    'options' => array(
      'attributes' => array(
        'title' => '微波炉',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 12,
    'parent_path' => 'taxonomy/term/86',
  );
  // Exported menu link: menu-category:taxonomy/term/73
  $menu_links['menu-category:taxonomy/term/73'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/73',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '五星级酒店',
    'options' => array(
      'attributes' => array(
        'title' => '五星级酒店',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 6,
    'parent_path' => 'taxonomy/term/106',
  );
  // Exported menu link: menu-category:taxonomy/term/74
  $menu_links['menu-category:taxonomy/term/74'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/74',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '肝胆用药',
    'options' => array(
      'attributes' => array(
        'title' => '肝胆用药',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 10,
    'parent_path' => 'taxonomy/term/200',
  );
  // Exported menu link: menu-category:taxonomy/term/75
  $menu_links['menu-category:taxonomy/term/75'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/75',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '租车公司',
    'options' => array(
      'attributes' => array(
        'title' => '租车公司',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 3,
    'parent_path' => 'taxonomy/term/126',
  );
  // Exported menu link: menu-category:taxonomy/term/76
  $menu_links['menu-category:taxonomy/term/76'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/76',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '补益安神',
    'options' => array(
      'attributes' => array(
        'title' => '补益安神',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 12,
    'parent_path' => 'taxonomy/term/200',
  );
  // Exported menu link: menu-category:taxonomy/term/77
  $menu_links['menu-category:taxonomy/term/77'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/77',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '蚕丝被',
    'options' => array(
      'attributes' => array(
        'title' => '蚕丝被',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 0,
    'parent_path' => 'taxonomy/term/65',
  );
  // Exported menu link: menu-category:taxonomy/term/78
  $menu_links['menu-category:taxonomy/term/78'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/78',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '木地板',
    'options' => array(
      'attributes' => array(
        'title' => '木地板',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 5,
    'parent_path' => 'taxonomy/term/109',
  );
  // Exported menu link: menu-category:taxonomy/term/79
  $menu_links['menu-category:taxonomy/term/79'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/79',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '多用途锅',
    'options' => array(
      'attributes' => array(
        'title' => '多用途锅',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 6,
    'parent_path' => 'taxonomy/term/86',
  );
  // Exported menu link: menu-category:taxonomy/term/8
  $menu_links['menu-category:taxonomy/term/8'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/8',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '阿胶',
    'options' => array(
      'attributes' => array(
        'title' => '阿胶',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 6,
    'parent_path' => 'taxonomy/term/170',
  );
  // Exported menu link: menu-category:taxonomy/term/80
  $menu_links['menu-category:taxonomy/term/80'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/80',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '板材',
    'options' => array(
      'attributes' => array(
        'title' => '板材',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => 1,
    'parent_path' => 'taxonomy/term/19',
  );
  // Exported menu link: menu-category:taxonomy/term/81
  $menu_links['menu-category:taxonomy/term/81'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/81',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '运动户外',
    'options' => array(
      'attributes' => array(
        'title' => '运动户外',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => 286,
  );
  // Exported menu link: menu-category:taxonomy/term/82
  $menu_links['menu-category:taxonomy/term/82'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/82',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '阳台窗',
    'options' => array(
      'attributes' => array(
        'title' => '阳台窗',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => 8,
    'parent_path' => 'taxonomy/term/19',
  );
  // Exported menu link: menu-category:taxonomy/term/83
  $menu_links['menu-category:taxonomy/term/83'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/83',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '燕窝',
    'options' => array(
      'attributes' => array(
        'title' => '燕窝',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 11,
    'parent_path' => 'taxonomy/term/170',
  );
  // Exported menu link: menu-category:taxonomy/term/84
  $menu_links['menu-category:taxonomy/term/84'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/84',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '开关套餐',
    'options' => array(
      'attributes' => array(
        'title' => '开关套餐',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 2,
    'parent_path' => 'taxonomy/term/121',
  );
  // Exported menu link: menu-category:taxonomy/term/85
  $menu_links['menu-category:taxonomy/term/85'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/85',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '增压泵',
    'options' => array(
      'attributes' => array(
        'title' => '增压泵',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 2,
    'parent_path' => 'taxonomy/term/221',
  );
  // Exported menu link: menu-category:taxonomy/term/86
  $menu_links['menu-category:taxonomy/term/86'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/86',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '厨房电器',
    'options' => array(
      'attributes' => array(
        'title' => '厨房电器',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => 1,
    'parent_path' => 'taxonomy/term/48',
  );
  // Exported menu link: menu-category:taxonomy/term/87
  $menu_links['menu-category:taxonomy/term/87'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/87',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '橱柜',
    'options' => array(
      'attributes' => array(
        'title' => '橱柜',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 2,
    'parent_path' => 'taxonomy/term/252',
  );
  // Exported menu link: menu-category:taxonomy/term/88
  $menu_links['menu-category:taxonomy/term/88'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/88',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '腰靠垫',
    'options' => array(
      'attributes' => array(
        'title' => '腰靠垫',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 0,
    'parent_path' => 'taxonomy/term/65',
  );
  // Exported menu link: menu-category:taxonomy/term/89
  $menu_links['menu-category:taxonomy/term/89'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/89',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '电压力锅',
    'options' => array(
      'attributes' => array(
        'title' => '电压力锅',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 10,
    'parent_path' => 'taxonomy/term/86',
  );
  // Exported menu link: menu-category:taxonomy/term/9
  $menu_links['menu-category:taxonomy/term/9'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/9',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '美容化妆',
    'options' => array(
      'attributes' => array(
        'title' => '美容化妆',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => 285,
  );
  // Exported menu link: menu-category:taxonomy/term/90
  $menu_links['menu-category:taxonomy/term/90'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/90',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '铝钛合金',
    'options' => array(
      'attributes' => array(
        'title' => '铝钛合金',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 2,
    'parent_path' => 'taxonomy/term/255',
  );
  // Exported menu link: menu-category:taxonomy/term/91
  $menu_links['menu-category:taxonomy/term/91'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/91',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '电子表',
    'options' => array(
      'attributes' => array(
        'title' => '电子表',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 2,
    'parent_path' => 'taxonomy/term/130',
  );
  // Exported menu link: menu-category:taxonomy/term/92
  $menu_links['menu-category:taxonomy/term/92'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/92',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '汽车电子',
    'options' => array(
      'attributes' => array(
        'title' => '汽车电子',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 0,
    'parent_path' => 'taxonomy/term/128',
  );
  // Exported menu link: menu-category:taxonomy/term/93
  $menu_links['menu-category:taxonomy/term/93'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/93',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '妇科用药',
    'options' => array(
      'attributes' => array(
        'title' => '妇科用药',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 8,
    'parent_path' => 'taxonomy/term/200',
  );
  // Exported menu link: menu-category:taxonomy/term/94
  $menu_links['menu-category:taxonomy/term/94'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/94',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '皮肤用药',
    'options' => array(
      'attributes' => array(
        'title' => '皮肤用药',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 2,
    'parent_path' => 'taxonomy/term/200',
  );
  // Exported menu link: menu-category:taxonomy/term/95
  $menu_links['menu-category:taxonomy/term/95'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/95',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '内墙砖',
    'options' => array(
      'attributes' => array(
        'title' => '内墙砖',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 5,
    'parent_path' => 'taxonomy/term/68',
  );
  // Exported menu link: menu-category:taxonomy/term/96
  $menu_links['menu-category:taxonomy/term/96'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/96',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '维生素c',
    'options' => array(
      'attributes' => array(
        'title' => '维生素c',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 4,
    'parent_path' => 'taxonomy/term/217',
  );
  // Exported menu link: menu-category:taxonomy/term/97
  $menu_links['menu-category:taxonomy/term/97'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/97',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '不锈钢',
    'options' => array(
      'attributes' => array(
        'title' => '不锈钢',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 5,
    'parent_path' => 'taxonomy/term/255',
  );
  // Exported menu link: menu-category:taxonomy/term/98
  $menu_links['menu-category:taxonomy/term/98'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/98',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '眼镜',
    'options' => array(
      'attributes' => array(
        'title' => '眼镜',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 1,
    'expanded' => 1,
    'weight' => 1,
    'parent_path' => 'taxonomy/term/137',
  );
  // Exported menu link: menu-category:taxonomy/term/99
  $menu_links['menu-category:taxonomy/term/99'] = array(
    'menu_name' => 'menu-category',
    'link_path' => 'taxonomy/term/99',
    'router_path' => 'taxonomy/term/%',
    'link_title' => '集成吊顶',
    'options' => array(
      'attributes' => array(
        'title' => '集成吊顶',
      ),
    ),
    'module' => 'taxonomy_menu',
    'hidden' => 0,
    'external' => 0,
    'has_children' => 0,
    'expanded' => 1,
    'weight' => 1,
    'parent_path' => 'taxonomy/term/5',
  );
  // Translatables
  // Included for use with string extractors like potx.
  t('1段奶粉');
  t('3D眼镜');
  t('T区');
  t('b族维生素');
  t('三七');
  t('三星级酒店');
  t('三角阀/煤气阀');
  t('下水管配件');
  t('不锈钢');
  t('中医保健');
  t('中西药品');
  t('乳液');
  t('五官用药');
  t('五星级酒店');
  t('五金');
  t('人参');
  t('仿古砖');
  t('传统滋补');
  t('体检/检测');
  t('保健品');
  t('保健理疗');
  t('光能表');
  t('免漆门');
  t('全棉四件套');
  t('公寓式酒店');
  t('内墙乳胶漆');
  t('内墙砖');
  t('冬虫夏草');
  t('净水器');
  t('凉席');
  t('刨花板');
  t('前置过滤器');
  t('医疗用品');
  t('医药保健');
  t('单芯线');
  t('单门');
  t('卫浴');
  t('卫浴五金');
  t('卵磷脂');
  t('卸妆');
  t('厨房');
  t('厨房电器');
  t('双门');
  t('口腔护理');
  t('台灯');
  t('台盆/立柱');
  t('吊灯');
  t('吊顶');
  t('吸顶灯');
  t('咖啡机');
  t('品牌女装');
  t('四星级酒店');
  t('地坪漆');
  t('地板');
  t('地板漆');
  t('地漏');
  t('地热地板');
  t('地砖');
  t('垃圾处理器');
  t('塑料');
  t('塑胶地板');
  t('墙砖');
  t('墙纸');
  t('增压泵');
  t('壁灯');
  t('复合维生素');
  t('外墙乳胶漆');
  t('外墙砖');
  t('多层木地板');
  t('多用途锅');
  t('夜视镜');
  t('大家电');
  t('大豆异黄酮');
  t('太阳眼镜');
  t('奶粉');
  t('妇科用药');
  t('婚庆套件');
  t('子母门');
  t('孕婴用药');
  t('定制衣柜');
  t('实木原木门');
  t('实木合工艺门');
  t('实木地板');
  t('家具建材');
  t('家庭器械');
  t('家用电器');
  t('家纺居家');
  t('对开门');
  t('居家拖鞋');
  t('布线箱');
  t('平板电视');
  t('床单');
  t('床垫');
  t('度假村');
  t('座便器');
  t('开关');
  t('开关/插座');
  t('开关套餐');
  t('强化复合地板');
  t('微波炉');
  t('性保健用品');
  t('感冒咳嗽');
  t('成品衣柜');
  t('戒烟用药');
  t('户外');
  t('房门');
  t('手机数码');
  t('手机通讯');
  t('手表');
  t('手表眼镜');
  t('抗菌洗液');
  t('拖把斗');
  t('排卵试纸');
  t('接线板');
  t('插座');
  t('整体衣柜');
  t('料理机/榨汁机');
  t('断路器');
  t('旅游公司');
  t('旅游度假');
  t('旅游网站');
  t('旅行箱包');
  t('无框');
  t('早孕试纸');
  t('时尚女鞋');
  t('春秋毯');
  t('春秋被');
  t('智能坐便盖');
  t('晾衣架');
  t('有框');
  t('服装配饰');
  t('服饰配件');
  t('木器漆');
  t('木地板');
  t('木塑地板');
  t('木方');
  t('木皮');
  t('木龙骨');
  t('机械表');
  t('机油润滑油');
  t('板材');
  t('枕套');
  t('枸杞');
  t('模压门');
  t('橡胶地板');
  t('橱柜');
  t('橱柜五金');
  t('母婴用品');
  t('毛浴巾');
  t('水槽');
  t('水泥');
  t('水管');
  t('汽车保养');
  t('汽车用品');
  t('汽车电子');
  t('油漆涂料');
  t('泌尿生殖');
  t('洁面');
  t('洗衣柜');
  t('流行男鞋');
  t('浴室柜');
  t('浴缸');
  t('润唇膏');
  t('润滑剂');
  t('淋浴房');
  t('淋浴花洒');
  t('温度计类');
  t('潮流女包');
  t('灯具');
  t('煮蛋器');
  t('燕窝');
  t('爽肤水');
  t('牛奶');
  t('牛奶乳品');
  t('玻化砖');
  t('珠宝饰品');
  t('瓷砖');
  t('生态板');
  t('生活电器');
  t('电压力锅');
  t('电子表');
  t('电水壶/热水瓶');
  t('电烤箱');
  t('电磁炉');
  t('电线');
  t('电缆线');
  t('电脑护目镜');
  t('电话线');
  t('电饭煲');
  t('电饼铛/煎烤机');
  t('男科用药');
  t('皮肤用药');
  t('眩晕晕车');
  t('眼部保养');
  t('眼镜');
  t('石子/砖');
  t('石膏板');
  t('石英表');
  t('租车公司');
  t('移门衣柜');
  t('竹地板');
  t('筒灯/射灯');
  t('签证公司');
  t('精华');
  t('精品家纺');
  t('精品男包');
  t('精品男装');
  t('精品酒店');
  t('精致内衣');
  t('紧急避孕');
  t('红景天');
  t('纱窗');
  t('细木工板');
  t('经济型酒店');
  t('维生素c');
  t('维生素e');
  t('维矿物质');
  t('网络线');
  t('美容化妆');
  t('老花眼镜');
  t('肝胆用药');
  t('肠胃用药');
  t('胶原蛋白');
  t('胶水');
  t('腰靠垫');
  t('膳食纤维');
  t('航空铝');
  t('花砖');
  t('花草枕');
  t('落地灯');
  t('葡萄籽素');
  t('虫草花');
  t('蚊帐');
  t('蚕丝被');
  t('蛋白粉');
  t('蜂花粉');
  t('蜂蜜');
  t('螺旋藻');
  t('血压仪器');
  t('血糖仪器');
  t('补益安神');
  t('被套');
  t('西洋参');
  t('解热镇痛');
  t('计生用品');
  t('记忆枕');
  t('豆浆机');
  t('蹲便器');
  t('轮椅拐杖');
  t('软木地板');
  t('软水机');
  t('辅料');
  t('运动户外');
  t('运动用品');
  t('运动鞋服');
  t('近视眼镜');
  t('遮阳产品');
  t('避孕套');
  t('酒店住宿');
  t('酸奶机');
  t('釉面砖');
  t('钙');
  t('钱包卡套');
  t('钻石');
  t('钻石珠宝');
  t('铁皮/石斛');
  t('铝合金');
  t('铝扣板');
  t('铝钛合金');
  t('镁铝合金');
  t('门中门');
  t('门锁/五金');
  t('防晒');
  t('防盗窗');
  t('防盗门');
  t('防静电地板');
  t('阳光房');
  t('阳台砖');
  t('阳台窗');
  t('阿胶');
  t('隔断移门');
  t('集成吊顶');
  t('集成材');
  t('雪蛤');
  t('青年旅舍');
  t('面包机');
  t('面膜');
  t('面部护肤');
  t('面霜');
  t('鞋帽箱包');
  t('音响线');
  t('风湿骨伤');
  t('食品饮料');
  t('饰面板');
  t('高丽参');
  t('鱼油');
  t('鹿茸');
  t('黄沙');
  t('龙头');


  return $menu_links;
}
